(() => {
'use strict';
const STORAGE_KEY='havensReachGraphicalProofV1', DATA_VERSION=1, REPAIR_COST_PER_POINT=10;
const LOCATIONS=new Set(['haven','meridian','prospect','calder']);
const DOCKABLE=new Set(['haven','meridian','prospect']);
const freshState=()=>({app:'havens-reach-graphical',dataVersion:DATA_VERSION,location:'haven',operatorLocation:'aboard',condition:'stationary',credits:700,ship:{id:'wayfarer',name:'Wayfarer',hull:92,hullMax:100,fuel:80,fuelMax:80,cargoCapacity:8},npcs:{seli:{met:false,relationship:0,memory:{}}},cargo:{},activeContract:null,completedContracts:[],reputation:0,discovery:{outerBeacon:{status:'unknown',reportsCompared:0},knownLocations:['haven','meridian','prospect']}});
function validState(c){return Boolean(c&&c.app==='havens-reach-graphical'&&c.dataVersion===DATA_VERSION&&LOCATIONS.has(c.location)&&['aboard','meridian-dock','last-lantern'].includes(c.operatorLocation)&&Number.isFinite(c.credits)&&c.credits>=0&&c.ship&&c.ship.id==='wayfarer'&&Number.isFinite(c.ship.hull)&&Number.isFinite(c.ship.hullMax)&&c.ship.hull>=0&&c.ship.hull<=c.ship.hullMax);}
function load(){try{const raw=localStorage.getItem(STORAGE_KEY);if(!raw)return freshState();const parsed=JSON.parse(raw);return validState(parsed)?parsed:freshState();}catch(error){console.warn('Graphical proof save could not be loaded; using a fresh proof state.',error);return freshState();}}
let state=load(), listeners=new Set();
function snapshot(){return typeof structuredClone==='function'?structuredClone(state):JSON.parse(JSON.stringify(state));}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));}
function notify(){const current=snapshot();listeners.forEach(fn=>fn(current));}
function ensureSeli(){if(!state.npcs||typeof state.npcs!=='object')state.npcs={};if(!state.npcs.seli||typeof state.npcs.seli!=='object')state.npcs.seli={met:false,relationship:0,memory:{}};if(!state.npcs.seli.memory||typeof state.npcs.seli.memory!=='object')state.npcs.seli.memory={};if(!Number.isFinite(state.npcs.seli.relationship))state.npcs.seli.relationship=0;state.npcs.seli.met=Boolean(state.npcs.seli.met);}
function ensureWorkState(){if(!state.cargo||typeof state.cargo!=='object')state.cargo={};if(!Array.isArray(state.completedContracts))state.completedContracts=[];if(!Number.isFinite(state.reputation))state.reputation=0;if(!('activeContract'in state))state.activeContract=null;}
function ensureDiscovery(){if(!state.discovery||typeof state.discovery!=='object')state.discovery={};if(!state.discovery.outerBeacon||typeof state.discovery.outerBeacon!=='object')state.discovery.outerBeacon={status:'unknown',reportsCompared:0};if(!Array.isArray(state.discovery.knownLocations))state.discovery.knownLocations=['haven','meridian','prospect'];['haven','meridian','prospect'].forEach(id=>{if(!state.discovery.knownLocations.includes(id))state.discovery.knownLocations.push(id);});if(state.discovery.outerBeacon.status==='confirmed'&&!state.discovery.knownLocations.includes('calder'))state.discovery.knownLocations.push('calder');}
ensureSeli();ensureWorkState();ensureDiscovery();
const SUPPLY_RUN={id:'haven-food',title:'Supply Run',destination:'meridian',reward:220,cargo:{food:2},rep:1,text:'A family-owned canteen needs packaged food delivered to Meridian Exchange.'};
function cargoUsed(){ensureWorkState();return Object.values(state.cargo).reduce((sum,qty)=>sum+(Number.isFinite(qty)?qty:0),0);}
function acceptSupplyRun(){ensureWorkState();if(state.location!=='haven'||state.operatorLocation!=='aboard'||state.activeContract)return{ok:false,state:snapshot()};if(cargoUsed()+2>state.ship.cargoCapacity)return{ok:false,reason:'cargo',state:snapshot()};state.cargo.food=(state.cargo.food||0)+2;state.activeContract={...SUPPLY_RUN,cargo:{...SUPPLY_RUN.cargo}};save();notify();return{ok:true,state:snapshot()};}
function completeSupplyRun(){ensureWorkState();const c=state.activeContract;if(!c||c.id!==SUPPLY_RUN.id||state.location!=='meridian'||state.condition!=='docked'||state.operatorLocation!=='aboard')return{ok:false,state:snapshot()};state.cargo.food=Math.max(0,(state.cargo.food||0)-2);if(!state.cargo.food)delete state.cargo.food;state.credits+=c.reward;state.reputation+=c.rep;if(!state.completedContracts.includes(c.id))state.completedContracts.push(c.id);state.activeContract=null;save();notify();return{ok:true,state:snapshot()};}
function workStatus(){ensureWorkState();return{supplyRun:{...SUPPLY_RUN,cargo:{...SUPPLY_RUN.cargo}},cargoUsed:cargoUsed(),cargoCapacity:state.ship.cargoCapacity};}
function known(destination){ensureDiscovery();return state.discovery.knownLocations.includes(destination);}
function beginTravel(destination){if(!LOCATIONS.has(destination)||!known(destination)||destination===state.location||state.condition!=='stationary'||state.operatorLocation!=='aboard')return{ok:false,state:snapshot()};state={...state,condition:'traveling'};notify();return{ok:true,origin:state.location,destination,state:snapshot()};}
function completeTravel(destination){if(!LOCATIONS.has(destination)||!known(destination)||state.condition!=='traveling')return{ok:false,state:snapshot()};state={...state,location:destination,condition:'stationary',operatorLocation:'aboard'};save();notify();return{ok:true,state:snapshot()};}
function cancelTravel(){if(state.condition!=='traveling')return{ok:false,state:snapshot()};state={...state,condition:'stationary'};notify();return{ok:true,state:snapshot()};}
function dock(){if(state.condition!=='stationary'||!DOCKABLE.has(state.location)||state.operatorLocation!=='aboard')return{ok:false,state:snapshot()};state={...state,condition:'docked'};save();notify();return{ok:true,state:snapshot()};}
function undock(){if(state.condition!=='docked'||state.operatorLocation!=='aboard')return{ok:false,state:snapshot()};state={...state,condition:'stationary'};save();notify();return{ok:true,state:snapshot()};}
function exitShip(){if(state.condition!=='docked'||state.operatorLocation!=='aboard'||!['meridian','prospect'].includes(state.location))return{ok:false,state:snapshot()};state={...state,operatorLocation:state.location==='meridian'?'meridian-dock':'last-lantern'};save();notify();return{ok:true,state:snapshot()};}
function returnToShip(){if(state.condition!=='docked'||!['meridian-dock','last-lantern'].includes(state.operatorLocation))return{ok:false,state:snapshot()};state={...state,operatorLocation:'aboard'};save();notify();return{ok:true,state:snapshot()};}
function compareOuterBeaconReports(){ensureDiscovery();if(state.location!=='prospect'||state.operatorLocation!=='last-lantern')return{ok:false,state:snapshot()};const d=state.discovery.outerBeacon;if(d.status==='confirmed')return{ok:false,state:snapshot()};d.status='confirmed';d.reportsCompared=3;d.note='Three independent survey crews reported the same faint navigation beacon coordinates beyond regular Prospect lanes.';if(!state.discovery.knownLocations.includes('calder'))state.discovery.knownLocations.push('calder');save();notify();return{ok:true,state:snapshot()};}
function chooseSeliFirstMeeting(choice){ensureSeli();const seli=state.npcs.seli;if(seli.met||!['share','private'].includes(choice))return{ok:false,state:snapshot()};seli.met=true;if(choice==='share'){seli.relationship+=1;seli.memory.sharedMarketNotes=true;}else seli.memory.keptNotesPrivate=true;save();notify();return{ok:true,state:snapshot()};}
function repairQuote(){const missing=Math.max(0,state.ship.hullMax-state.ship.hull),affordablePoints=Math.floor(state.credits/REPAIR_COST_PER_POINT),repairPoints=Math.min(missing,affordablePoints);return{missing,repairPoints,cost:repairPoints*REPAIR_COST_PER_POINT,fullCost:missing*REPAIR_COST_PER_POINT,canRepair:repairPoints>0};}
function repairHull(){const quote=repairQuote();if(state.location!=='haven'||!quote.canRepair)return{ok:false,quote};state={...state,credits:state.credits-quote.cost,ship:{...state.ship,hull:state.ship.hull+quote.repairPoints}};save();notify();return{ok:true,quote,state:snapshot()};}
function subscribe(listener){listeners.add(listener);return()=>listeners.delete(listener);}
window.HRState={get:snapshot,beginTravel,completeTravel,cancelTravel,dock,undock,exitShip,returnToShip,compareOuterBeaconReports,chooseSeliFirstMeeting,acceptSupplyRun,completeSupplyRun,workStatus,repairQuote,repairHull,subscribe,save};
})();