(() => {
'use strict';
const STORAGE_KEY='havensReachGraphicalProofV1',DATA_VERSION=1,REPAIR_COST_PER_POINT=10;
const TRADE_MARKETS={haven:{food:{buy:45,sell:35},machineParts:{buy:80,sell:70},medicine:{buy:70,sell:60}},meridian:{food:{buy:65,sell:55},machineParts:{buy:60,sell:50},medicine:{buy:75,sell:65}}};
const FIELD_LOCATION='gowl-distress-field';
const LOCATIONS=new Set(['haven','meridian','prospect','calder',FIELD_LOCATION]),DOCKABLE=new Set(['haven','meridian','prospect']),SERVICED=new Set(['haven','meridian','prospect']),ROUTES={haven:{meridian:18},meridian:{haven:18,prospect:25},prospect:{meridian:25,calder:22},calder:{prospect:22,[FIELD_LOCATION]:12},[FIELD_LOCATION]:{calder:12}};
const CONTRACTS={
 haven:[
  {id:'haven-food',title:'Supply Run',destination:'meridian',reward:220,cargo:{food:2},rep:1,text:'A family-owned canteen needs packaged food delivered to Meridian Exchange.'},
  {id:'haven-survey',title:'Survey Data Courier',destination:'prospect',reward:420,cargo:{},rep:1,text:'Carry sealed geological survey data to Prospect Reach.'},
  {id:'haven-family-parcels',title:'Frontier Family Parcels',destination:'prospect',reward:390,cargo:{},rep:1,text:'Carry a consolidated packet of family parcels and recorded messages from Haven to workers at Prospect Reach.'}
 ],
 meridian:[
  {id:'meridian-parts',title:'Machine Parts Delivery',destination:'prospect',reward:310,cargo:{machineParts:2},rep:1,text:'A Kharok maintenance crew is short on replacement actuator assemblies.'},
  {id:'meridian-meds',title:'Medical Priority',destination:'haven',reward:260,cargo:{medicine:1},rep:1,text:'A clinic on Haven needs a small urgent shipment of medication.'},
  {id:'meridian-canteen-stock',title:'Canteen Restock',destination:'prospect',reward:335,cargo:{food:2},rep:1,text:"Prospect's main canteen is short on packaged staples after a delayed supply run."}
 ],
 prospect:[
  {id:'prospect-samples',title:'Salvage Samples',destination:'meridian',reward:360,cargo:{},rep:1,text:'Transport recovered drive components to a buyer at Meridian Exchange.'},
  {id:'prospect-home',title:'Letter Packet',destination:'haven',reward:180,cargo:{},rep:1,text:'Carry personal correspondence from frontier workers back toward Haven.'},
  {id:'prospect-relay-spares',title:'Relay Spare Set',destination:'calder',reward:405,cargo:{machineParts:1},rep:1,text:"A navigation crew at Calder's Drift needs a compact set of relay spares before its next maintenance pass."}
 ]};
const SELI_PRIVATE_JOB={id:'seli-private-freight',title:'Seli’s Private Freight',destination:'haven',reward:280,cargo:{food:2},rep:1,text:'A Meridian commercial client has entrusted Seli with a small shipment of packaged provisions for Haven. The client needs a dependable independent operator.',privateReferral:true};
const PRECISION_JOB={id:'meridian-precision-instrument',title:'Precision Instrument Transfer',destination:'prospect',reward:460,cargo:{precisionInstrument:2},rep:1,requiredPackage:'freight-handling-package',text:'A sealed precision instrument must reach Prospect’s research facility. Stabilized environmental handling is essential; ordinary cargo restraints are insufficient.'};
const freshState=()=>({app:'havens-reach-graphical',dataVersion:DATA_VERSION,setupComplete:false,captain:{name:''},location:'haven',operatorLocation:'aboard',condition:'stationary',credits:700,ship:{id:'wayfarer',name:'Wayfarer',hull:92,hullMax:100,fuel:80,fuelMax:80,fuelEfficiency:1,cargoCapacity:8,specialization:{installed:null,owned:[]}},npcs:{seli:{met:false,relationship:0,memory:{}},mara:{met:false,memory:{}},brann:{met:false,memory:{}},gowlDistress:{met:false,memory:{}},tavyrel:{met:false,memory:{}}},fieldOperations:{gowlDistress:{status:'unavailable',outcome:null,signalSeen:false}},cargo:{},tradeCargo:{},tradeCargoCost:{},marketRecords:{},activeContract:null,completedContracts:[],reputation:0,tripCount:0,contractBoards:{},discovery:{outerBeacon:{status:'unknown',reportsCompared:0},knownLocations:['haven','meridian','prospect'],calderSurvey:{stage:'unexamined',archiveRecovered:false,sharedWithSeli:false}},stationDevelopment:{haven:{oldGantry:{status:'unknown'}},prospect:{researchInstrumentDelivered:false}}});
function validState(c){return Boolean(c&&c.app==='havens-reach-graphical'&&c.dataVersion===DATA_VERSION&&LOCATIONS.has(c.location)&&['aboard','haven-repair-bay','haven-commons','haven-old-gantry','meridian-dock','last-lantern'].includes(c.operatorLocation)&&Number.isFinite(c.credits)&&c.credits>=0&&c.ship&&c.ship.id==='wayfarer'&&Number.isFinite(c.ship.hull)&&Number.isFinite(c.ship.hullMax)&&c.ship.hull>=0&&c.ship.hull<=c.ship.hullMax);}
function migrateIdentity(parsed){if(!parsed||typeof parsed!=='object')return parsed;if(!parsed.captain||typeof parsed.captain!=='object')parsed.captain={name:''};if(typeof parsed.captain.name!=='string')parsed.captain.name='';if(parsed.ship&&typeof parsed.ship.name!=='string')parsed.ship.name='Wayfarer';if(parsed.ship){if(!parsed.ship.specialization||typeof parsed.ship.specialization!=='object')parsed.ship.specialization={installed:null,owned:[]};const spec=parsed.ship.specialization;if(!Array.isArray(spec.owned))spec.owned=[];spec.owned=[...new Set(spec.owned.filter(id=>['survey-package','freight-handling-package'].includes(id)))];if(!['survey-package','freight-handling-package'].includes(spec.installed))spec.installed=null;if(spec.installed&&!spec.owned.includes(spec.installed))spec.owned.push(spec.installed);}if(parsed.discovery?.calderSurvey?.archiveRecovered){if(!parsed.discovery.specializedSurvey||typeof parsed.discovery.specializedSurvey!=='object')parsed.discovery.specializedSurvey={status:'known',completed:false};}if(!parsed.stationDevelopment||typeof parsed.stationDevelopment!=='object')parsed.stationDevelopment={};if(!parsed.stationDevelopment.prospect||typeof parsed.stationDevelopment.prospect!=='object')parsed.stationDevelopment.prospect={researchInstrumentDelivered:false};parsed.stationDevelopment.prospect.researchInstrumentDelivered=Boolean(parsed.stationDevelopment.prospect.researchInstrumentDelivered||parsed.completedContracts?.includes(PRECISION_JOB.id));if(typeof parsed.setupComplete!=='boolean')parsed.setupComplete=true;return parsed;}
let loadFailure=null;
function load(){try{const raw=localStorage.getItem(STORAGE_KEY);if(!raw)return freshState();const parsed=migrateIdentity(JSON.parse(raw));if(!validState(parsed))throw new Error('Saved game failed validation.');return parsed;}catch(error){loadFailure=error;console.error('Saved game could not be loaded. Existing local data has been left untouched.',error);return freshState();}}
let state=load(),listeners=new Set(),pendingTravel=null;
function snapshot(){return typeof structuredClone==='function'?structuredClone(state):JSON.parse(JSON.stringify(state));}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));}
function notify(){const current=snapshot();listeners.forEach(fn=>fn(current));}
function normalizedIdentity(captainName,shipName){const captain=String(captainName||'').trim().replace(/\s+/g,' '),ship=String(shipName||'').trim().replace(/\s+/g,' ');if(!captain)return{ok:false,reason:'captain-required'};if(!ship)return{ok:false,reason:'ship-required'};if(captain.length>40||ship.length>40)return{ok:false,reason:'name-too-long'};return{ok:true,captain,ship};}
function completeSetup(captainName,shipName){if(state.setupComplete)return{ok:false,reason:'already-complete',state:snapshot()};const identity=normalizedIdentity(captainName,shipName);if(!identity.ok)return{...identity,state:snapshot()};state={...state,setupComplete:true,captain:{name:identity.captain},ship:{...state.ship,name:identity.ship}};save();notify();return{ok:true,state:snapshot()};}
function beginNewPlaythrough(captainName,shipName){const identity=normalizedIdentity(captainName,shipName);if(!identity.ok)return{...identity,state:snapshot()};const replacement=freshState();replacement.setupComplete=true;replacement.captain.name=identity.captain;replacement.ship.name=identity.ship;try{localStorage.setItem(STORAGE_KEY,JSON.stringify(replacement));}catch(error){console.error('New playthrough could not be created. Existing saved game has been left untouched.',error);return{ok:false,reason:'write-failed',state:snapshot()};}state=replacement;pendingTravel=null;loadFailure=null;notify();return{ok:true,state:snapshot()};}
function ensureSeli(){if(!state.npcs||typeof state.npcs!=='object')state.npcs={};if(!state.npcs.seli||typeof state.npcs.seli!=='object')state.npcs.seli={met:false,relationship:0,memory:{}};if(!state.npcs.seli.memory||typeof state.npcs.seli.memory!=='object')state.npcs.seli.memory={};if(!Number.isFinite(state.npcs.seli.relationship))state.npcs.seli.relationship=0;state.npcs.seli.met=Boolean(state.npcs.seli.met);}
function ensureMara(){if(!state.npcs||typeof state.npcs!=='object')state.npcs={};if(!state.npcs.mara||typeof state.npcs.mara!=='object')state.npcs.mara={met:false,memory:{}};if(!state.npcs.mara.memory||typeof state.npcs.mara.memory!=='object')state.npcs.mara.memory={};state.npcs.mara.met=Boolean(state.npcs.mara.met);}
function ensureBrann(){if(!state.npcs||typeof state.npcs!=='object')state.npcs={};if(!state.npcs.brann||typeof state.npcs.brann!=='object')state.npcs.brann={met:false,memory:{}};if(!state.npcs.brann.memory||typeof state.npcs.brann.memory!=='object')state.npcs.brann.memory={};state.npcs.brann.met=Boolean(state.npcs.brann.met);}
function ensureFieldOperation(){if(!state.fieldOperations||typeof state.fieldOperations!=='object')state.fieldOperations={};if(!state.fieldOperations.gowlDistress||typeof state.fieldOperations.gowlDistress!=='object')state.fieldOperations.gowlDistress={status:'unavailable',outcome:null};const op=state.fieldOperations.gowlDistress;if(typeof op.signalSeen!=='boolean')op.signalSeen=op.status!=='signal-received';if(!['unavailable','signal-received','coordinates-available','on-site','contact-established','resolved'].includes(op.status))op.status='unavailable';if(!state.npcs||typeof state.npcs!=='object')state.npcs={};if(!state.npcs.gowlDistress||typeof state.npcs.gowlDistress!=='object')state.npcs.gowlDistress={met:false,memory:{}};if(!state.npcs.gowlDistress.memory||typeof state.npcs.gowlDistress.memory!=='object')state.npcs.gowlDistress.memory={};if(state.discovery?.calderSurvey?.archiveRecovered&&op.status==='unavailable'){op.status='signal-received';op.signalSeen=false;}}
function ensureTavyrel(){
 if(!state.npcs||typeof state.npcs!=='object')state.npcs={};
 if(!state.npcs.tavyrel||typeof state.npcs.tavyrel!=='object')state.npcs.tavyrel={met:false,memory:{}};
 if(!state.npcs.tavyrel.memory||typeof state.npcs.tavyrel.memory!=='object')state.npcs.tavyrel.memory={};
 const t=state.npcs.tavyrel,m=state.npcs.gowlDistress?.memory||{},op=state.fieldOperations?.gowlDistress;
 if(state.npcs.gowlDistress?.met)t.met=true;
 if(op?.status==='resolved'){
  t.met=true;
  t.memory.answeredDistress=Boolean(m.answeredDistress);
  t.memory.rescued=Boolean(m.rescuedOperator);
  t.memory.vesselSaved=Boolean(m.vesselSaved);
  t.memory.vesselAbandoned=Boolean(m.vesselAbandoned);
  t.memory.wayfarerDamaged=Boolean(m.wayfarerDamaged);
  if(Number.isFinite(op.resolvedTrip)&&!Number.isFinite(t.memory.rescueResolvedTrip))t.memory.rescueResolvedTrip=op.resolvedTrip;
 }
}
function tavyrelContinuity(){
 ensureFieldOperation();ensureTavyrel();
 const t=state.npcs.tavyrel,op=state.fieldOperations.gowlDistress,resolvedTrip=Number.isFinite(t.memory.rescueResolvedTrip)?t.memory.rescueResolvedTrip:op.resolvedTrip;
 const legacyResolved=op.status==='resolved'&&!Number.isFinite(resolvedTrip);if(legacyResolved&&!Number.isFinite(t.memory.rescueResolvedTrip)){t.memory.rescueResolvedTrip=Math.max(0,state.tripCount-2);save();}const effectiveResolvedTrip=Number.isFinite(t.memory.rescueResolvedTrip)?t.memory.rescueResolvedTrip:resolvedTrip;const eligible=op.status==='resolved'&&Number.isFinite(effectiveResolvedTrip)&&state.tripCount>=effectiveResolvedTrip+2;
 return{name:'Tavyrel',met:t.met,eligibleForProspectReunion:eligible,reunionCompleted:Boolean(t.memory.metAgainAtLastLantern),rescueResolvedTrip:Number.isFinite(effectiveResolvedTrip)?effectiveResolvedTrip:null,outcome:op.outcome,vesselSaved:Boolean(t.memory.vesselSaved),vesselAbandoned:Boolean(t.memory.vesselAbandoned),wayfarerDamaged:Boolean(t.memory.wayfarerDamaged)};
}
function completeTavyrelReunion(){
 ensureFieldOperation();ensureTavyrel();const c=tavyrelContinuity();
 if(state.operatorLocation!=='last-lantern'||!c.eligibleForProspectReunion)return{ok:false,state:snapshot()};
 const m=state.npcs.tavyrel.memory;if(!m.metAgainAtLastLantern){m.metAgainAtLastLantern=true;m.lastLanternReunionTrip=state.tripCount;save();notify();}
 return{ok:true,state:snapshot()};
}
function fieldOperation(){ensureFieldOperation();return JSON.parse(JSON.stringify(state.fieldOperations.gowlDistress));}
function acknowledgeCommunications(){ensureFieldOperation();const op=state.fieldOperations.gowlDistress;if(op.status==='signal-received'&&!op.signalSeen){op.signalSeen=true;save();notify();return{ok:true,state:snapshot()};}return{ok:false,state:snapshot()};}
function respondToDistress(){ensureFieldOperation();const op=state.fieldOperations.gowlDistress;if(op.status!=='signal-received'||state.operatorLocation!=='aboard'||state.condition!=='stationary')return{ok:false,state:snapshot()};op.status='coordinates-available';op.respondedTrip=state.tripCount;save();notify();return{ok:true,state:snapshot()};}
function establishDistressContact(){ensureFieldOperation();const op=state.fieldOperations.gowlDistress;if(state.location!==FIELD_LOCATION||state.operatorLocation!=='aboard'||state.condition!=='stationary'||op.status!=='on-site')return{ok:false,state:snapshot()};op.status='contact-established';state.npcs.gowlDistress.met=true;state.npcs.gowlDistress.memory.contactEstablished=true;save();notify();return{ok:true,state:snapshot()};}
function resolveDistress(choice){ensureFieldOperation();const op=state.fieldOperations.gowlDistress;if(state.location!==FIELD_LOCATION||state.operatorLocation!=='aboard'||state.condition!=='stationary'||op.status!=='contact-established'||!['rescue-operator','save-vessel'].includes(choice))return{ok:false,state:snapshot()};op.status='resolved';op.outcome=choice;op.resolvedTrip=state.tripCount;const memory=state.npcs.gowlDistress.memory;memory.answeredDistress=true;memory.rescuedOperator=true;if(choice==='save-vessel'){const damage=Math.min(8,state.ship.hull);state.ship.hull-=damage;op.hullDamage=damage;memory.vesselSaved=true;memory.wayfarerDamaged=true;}else{memory.vesselAbandoned=true;}ensureTavyrel();save();notify();return{ok:true,state:snapshot()};}
function ensureWorkState(){if(!state.cargo||typeof state.cargo!=='object')state.cargo={};if(!state.tradeCargo||typeof state.tradeCargo!=='object')state.tradeCargo={};if(!state.tradeCargoCost||typeof state.tradeCargoCost!=='object')state.tradeCargoCost={};if(!state.marketRecords||typeof state.marketRecords!=='object')state.marketRecords={};Object.entries(state.tradeCargo).forEach(([id,qty])=>{if(!(qty>0))delete state.tradeCargoCost[id];else if(!Object.prototype.hasOwnProperty.call(state.tradeCargoCost,id))state.tradeCargoCost[id]=null;});if(!Array.isArray(state.completedContracts))state.completedContracts=[];if(!Number.isFinite(state.reputation))state.reputation=0;if(!Number.isFinite(state.tripCount))state.tripCount=0;if(!state.contractBoards||typeof state.contractBoards!=='object')state.contractBoards={};if(!('activeContract'in state))state.activeContract=null;}
function ensureStationDevelopment(){if(!state.stationDevelopment||typeof state.stationDevelopment!=='object')state.stationDevelopment={};if(!state.stationDevelopment.haven||typeof state.stationDevelopment.haven!=='object')state.stationDevelopment.haven={};if(!state.stationDevelopment.haven.oldGantry||typeof state.stationDevelopment.haven.oldGantry!=='object')state.stationDevelopment.haven.oldGantry={status:'unknown'};const g=state.stationDevelopment.haven.oldGantry;if(!['unknown','revealed','inspected','lead-known','assembly-aboard','restoring','operational'].includes(g.status))g.status='unknown';if(g.status==='revealed'&&state.npcs?.mara?.memory?.toldAboutOldGantry&&Number.isFinite(g.revealedTrip)&&state.tripCount>g.revealedTrip){g.status='inspected';if(!Number.isFinite(g.inspectedTrip))g.inspectedTrip=g.revealedTrip;}if(typeof g.seliLeadKnown!=='boolean')g.seliLeadKnown=['lead-known','assembly-aboard'].includes(g.status);if(typeof g.assemblyPurchased!=='boolean')g.assemblyPurchased=['assembly-aboard','restoring','operational'].includes(g.status);if(typeof g.assemblyDelivered!=='boolean')g.assemblyDelivered=['restoring','operational'].includes(g.status);if(g.status==='restoring'&&Number.isFinite(g.restorationStartTrip)&&state.tripCount>=g.restorationStartTrip+2){g.status='operational';g.operationalTrip=g.restorationStartTrip+2;}}
function ensureDiscovery(){if(!state.discovery||typeof state.discovery!=='object')state.discovery={};if(!state.discovery.outerBeacon||typeof state.discovery.outerBeacon!=='object')state.discovery.outerBeacon={status:'unknown',reportsCompared:0};if(!Array.isArray(state.discovery.knownLocations))state.discovery.knownLocations=['haven','meridian','prospect'];['haven','meridian','prospect'].forEach(id=>{if(!state.discovery.knownLocations.includes(id))state.discovery.knownLocations.push(id);});if(state.discovery.outerBeacon.status==='confirmed'&&!state.discovery.knownLocations.includes('calder'))state.discovery.knownLocations.push('calder');if(!state.discovery.calderSurvey||typeof state.discovery.calderSurvey!=='object')state.discovery.calderSurvey={stage:'unexamined',archiveRecovered:false,sharedWithSeli:false};state.discovery.calderSurvey.archiveRecovered=Boolean(state.discovery.calderSurvey.archiveRecovered);state.discovery.calderSurvey.sharedWithSeli=Boolean(state.discovery.calderSurvey.sharedWithSeli);if(state.discovery.calderSurvey.archiveRecovered&&(!state.discovery.specializedSurvey||typeof state.discovery.specializedSurvey!=='object'))state.discovery.specializedSurvey={status:'known',completed:false};if(state.discovery.specializedSurvey){state.discovery.specializedSurvey.completed=Boolean(state.discovery.specializedSurvey.completed);state.discovery.specializedSurvey.status=state.discovery.specializedSurvey.completed?'completed':'known';}}
ensureSeli();ensureMara();ensureBrann();ensureWorkState();ensureDiscovery();ensureStationDevelopment();ensureFieldOperation();ensureTavyrel();ensureFuel();ensureShipSpecialization();
function cargoUsed(){ensureWorkState();return [state.cargo,state.tradeCargo].reduce((total,hold)=>total+Object.values(hold).reduce((sum,qty)=>sum+(Number.isFinite(qty)?qty:0),0),0);}
function cargoNeeded(contract){return Object.values(contract.cargo||{}).reduce((sum,qty)=>sum+qty,0);}
function known(destination){ensureDiscovery();ensureFieldOperation();if(destination===FIELD_LOCATION)return['coordinates-available','on-site','contact-established'].includes(state.fieldOperations.gowlDistress.status);return state.discovery.knownLocations.includes(destination);}
function ensureFuel(){if(!Number.isFinite(state.ship.fuelMax))state.ship.fuelMax=80;if(!Number.isFinite(state.ship.fuel))state.ship.fuel=state.ship.fuelMax;if(!Number.isFinite(state.ship.fuelEfficiency)||state.ship.fuelEfficiency<=0)state.ship.fuelEfficiency=1;state.ship.fuel=Math.max(0,Math.min(state.ship.fuel,state.ship.fuelMax));}
function routeDistance(start,goal){if(start===goal)return 0;const dist={[start]:0},open=[start];while(open.length){open.sort((a,b)=>dist[a]-dist[b]);const current=open.shift();if(current===goal)return dist[current];for(const [next,cost] of Object.entries(ROUTES[current]||{})){const candidate=dist[current]+cost;if(dist[next]===undefined||candidate<dist[next]){dist[next]=candidate;if(!open.includes(next))open.push(next);}}}return Infinity;}
function fuelCost(start,destination){ensureFuel();const distance=routeDistance(start,destination);return Number.isFinite(distance)?Math.ceil(distance*state.ship.fuelEfficiency):Infinity;}
function reserveFrom(destination){if(SERVICED.has(destination))return 0;let best=Infinity;for(const port of SERVICED){const cost=fuelCost(destination,port);if(cost<best)best=cost;}return best;}
function travelQuote(destination){ensureFuel();if(!LOCATIONS.has(destination)||!known(destination)||destination===state.location)return{ok:false,cost:Infinity,reserve:0};const cost=fuelCost(state.location,destination),reserve=reserveFrom(destination),required=cost+reserve;return{ok:state.ship.fuel>=required,cost,reserve,required,fuel:state.ship.fuel,fuelMax:state.ship.fuelMax,serviced:SERVICED.has(destination)};}
function refuelQuote(){ensureFuel();const needed=Math.max(0,state.ship.fuelMax-state.ship.fuel),units=Math.min(needed,Math.floor(state.credits));return{available:SERVICED.has(state.location)&&state.operatorLocation==='aboard'&&state.condition==='docked',needed,units,cost:units,fullCost:needed};}
function refuelToFull(){const q=refuelQuote();if(!q.available||q.units<=0)return{ok:false,quote:q,state:snapshot()};state.ship.fuel+=q.units;state.credits-=q.cost;save();notify();return{ok:true,quote:q,state:snapshot()};}
function shuffled(items){const copy=[...items];for(let i=copy.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]];}return copy;}
function sameSet(a=[],b=[]){return a.length===b.length&&[...a].sort().every((id,i)=>id===[...b].sort()[i]);}
function availablePool(location){return (CONTRACTS[location]||[]).filter(c=>known(c.destination));}
function workOffers(location=state.location){
 ensureWorkState();const pool=availablePool(location),ids=pool.map(c=>c.id),record=state.contractBoards[location];
 if(record&&record.trip===state.tripCount&&Array.isArray(record.offers)){const valid=record.offers.filter(id=>ids.includes(id));if(valid.length)return valid.map(id=>pool.find(c=>c.id===id)).filter(Boolean);}
 const limit=Math.min(2,pool.length);let offers=shuffled(ids).slice(0,limit),previous=record?.offers||[];
 if(pool.length>limit&&sameSet(offers,previous)){for(let n=0;n<5&&sameSet(offers,previous);n++)offers=shuffled(ids).slice(0,limit);}
 state.contractBoards[location]={trip:state.tripCount,offers:[...offers]};save();
 return offers.map(id=>pool.find(c=>c.id===id)).filter(Boolean);
}
function ensureSeliFreight(){ensureSeli();const m=state.npcs.seli.memory;if(!m.privateFreight||typeof m.privateFreight!=='object')m.privateFreight={referred:false,completed:0,lastDeliveryTrip:null};const f=m.privateFreight;f.referred=Boolean(f.referred);if(!Number.isInteger(f.completed)||f.completed<0)f.completed=0;if(!Number.isFinite(f.lastDeliveryTrip))f.lastDeliveryTrip=null;return f;}
function seliFreightStatus(){const f=ensureSeliFreight();const active=state.activeContract?.id===SELI_PRIVATE_JOB.id;return{referred:f.referred,completed:f.completed,active,available:f.referred&&state.location==='meridian'&&!active&&(f.lastDeliveryTrip===null||state.tripCount>=f.lastDeliveryTrip+2),remainingTrips:f.lastDeliveryTrip===null?0:Math.max(0,f.lastDeliveryTrip+2-state.tripCount)};}
function acceptSeliReferral(){const f=ensureSeliFreight();if(!state.npcs.seli.met||f.referred||state.location!=='meridian'||seliPresence()!=='meridian'||state.operatorLocation==='aboard')return{ok:false,state:snapshot()};f.referred=true;save();notify();return{ok:true,state:snapshot()};}
function precisionFreightStatus(){ensureWorkState();ensureShipSpecialization();return{delivered:Boolean(state.stationDevelopment?.prospect?.researchInstrumentDelivered||state.completedContracts.includes(PRECISION_JOB.id)),active:state.activeContract?.id===PRECISION_JOB.id,capable:state.ship.specialization.installed==='freight-handling-package'};}
function findContract(id){for(const pool of Object.values(CONTRACTS)){const found=pool.find(c=>c.id===id);if(found)return found;}return null;}
function acceptContract(id){
 ensureWorkState();const offer=id===SELI_PRIVATE_JOB.id&&seliFreightStatus().available?SELI_PRIVATE_JOB:id===PRECISION_JOB.id&&state.location==='meridian'&&!precisionFreightStatus().delivered?PRECISION_JOB:workOffers(state.location).find(c=>c.id===id);
 if(!offer||state.operatorLocation!=='aboard'||state.activeContract)return{ok:false,state:snapshot()};
 if(offer.requiredPackage&&state.ship.specialization.installed!==offer.requiredPackage)return{ok:false,reason:'specialization',state:snapshot()};
 if(cargoUsed()+cargoNeeded(offer)>state.ship.cargoCapacity)return{ok:false,reason:'cargo',state:snapshot()};
 Object.entries(offer.cargo||{}).forEach(([good,qty])=>state.cargo[good]=(state.cargo[good]||0)+qty);
 state.activeContract={...offer,cargo:{...(offer.cargo||{})},origin:state.location};save();notify();return{ok:true,state:snapshot()};
}
function canCompleteActive(){
 ensureWorkState();const c=state.activeContract;if(!c||c.destination!==state.location||state.operatorLocation!=='aboard')return false;
 return DOCKABLE.has(state.location)?state.condition==='docked':state.condition==='stationary';
}
function completeActiveContract(){
 ensureWorkState();const c=state.activeContract;if(!c||!canCompleteActive()||(c.requiredPackage&&state.ship.specialization.installed!==c.requiredPackage)||Object.entries(c.cargo||{}).some(([good,qty])=>!Number.isInteger(qty)||qty<0||(state.cargo[good]||0)<qty))return{ok:false,state:snapshot()};
 Object.entries(c.cargo||{}).forEach(([good,qty])=>{state.cargo[good]=Math.max(0,(state.cargo[good]||0)-qty);if(!state.cargo[good])delete state.cargo[good];});
 state.credits+=c.reward;state.reputation+=c.rep||0;state.completedContracts.push(c.id);if(c.id===SELI_PRIVATE_JOB.id){const f=ensureSeliFreight();f.completed+=1;f.lastDeliveryTrip=state.tripCount;state.npcs.seli.memory.privateFreightDelivered=true;state.npcs.seli.relationship+=1;}if(c.id===PRECISION_JOB.id){if(!state.stationDevelopment)state.stationDevelopment={};state.stationDevelopment.prospect={...(state.stationDevelopment.prospect||{}),researchInstrumentDelivered:true,deliveredTrip:state.tripCount};}state.activeContract=null;save();notify();return{ok:true,state:snapshot()};
}
function workStatus(){ensureWorkState();return{offers:[...workOffers(state.location),...(state.location==='meridian'&&!precisionFreightStatus().delivered?[PRECISION_JOB]:[]),...(seliFreightStatus().available?[SELI_PRIVATE_JOB]:[])].map(c=>({...c,cargo:{...(c.cargo||{})}})),cargoUsed:cargoUsed(),cargoCapacity:state.ship.cargoCapacity,canComplete:canCompleteActive()};}
function tradeMarket(){ensureWorkState();const market=TRADE_MARKETS[state.location],base={available:false,location:state.location,goods:{},credits:state.credits,cargoUsed:cargoUsed(),cargoCapacity:state.ship.cargoCapacity,owned:{...state.tradeCargo},costBasis:{...state.tradeCargoCost}};if(!market||!['haven-repair-bay','meridian-dock'].includes(state.operatorLocation))return base;return{...base,available:true,goods:JSON.parse(JSON.stringify(market))};}
function observeTradeMarket(){const q=tradeMarket();if(!q.available)return{ok:false,state:snapshot()};state.marketRecords[q.location]={observedTrip:state.tripCount,goods:JSON.parse(JSON.stringify(q.goods))};save();notify();return{ok:true,state:snapshot()};}
function marketRecords(){ensureWorkState();return JSON.parse(JSON.stringify(state.marketRecords));}
function tradeQuantity(value){const qty=Number(value);return Number.isInteger(qty)&&qty>0?qty:0;}
function buyTradeGood(id,quantity=1){const q=tradeMarket(),price=q.goods?.[id]?.buy,qty=tradeQuantity(quantity),free=q.cargoCapacity-q.cargoUsed;if(!q.available||!Number.isFinite(price)||!qty||qty>free||state.credits<price*qty)return{ok:false,state:snapshot()};const owned=state.tradeCargo[id]||0,prior=state.tradeCargoCost[id],newQty=owned+qty;state.credits-=price*qty;state.tradeCargo[id]=newQty;state.tradeCargoCost[id]=owned>0&&!Number.isFinite(prior)?null:((owned*(Number.isFinite(prior)?prior:0))+(qty*price))/newQty;save();notify();return{ok:true,quantity:qty,unitPrice:price,total:price*qty,state:snapshot()};}
function sellTradeGood(id,quantity=1){const q=tradeMarket(),price=q.goods?.[id]?.sell,qty=tradeQuantity(quantity),owned=state.tradeCargo[id]||0,basis=state.tradeCargoCost[id];if(!q.available||!Number.isFinite(price)||!qty||qty>owned)return{ok:false,state:snapshot()};state.tradeCargo[id]=owned-qty;state.credits+=price*qty;if(!state.tradeCargo[id]){delete state.tradeCargo[id];delete state.tradeCargoCost[id];}save();notify();return{ok:true,quantity:qty,unitPrice:price,total:price*qty,profit:Number.isFinite(basis)?(price-basis)*qty:null,state:snapshot()};}
function beginTravel(destination){const quote=travelQuote(destination);if(!quote.ok||state.condition!=='stationary'||state.operatorLocation!=='aboard')return{ok:false,quote,state:snapshot()};state.ship.fuel-=quote.cost;pendingTravel={cost:quote.cost};state={...state,condition:'traveling'};notify();return{ok:true,origin:state.location,destination,quote,state:snapshot()};}
function completeTravel(destination){if(!LOCATIONS.has(destination)||!known(destination)||state.condition!=='traveling')return{ok:false,state:snapshot()};state={...state,location:destination,condition:'stationary',operatorLocation:'aboard',tripCount:state.tripCount+1};if(destination===FIELD_LOCATION){ensureFieldOperation();state.fieldOperations.gowlDistress.status='on-site';}ensureStationDevelopment();pendingTravel=null;save();notify();return{ok:true,state:snapshot()};}
function cancelTravel(){if(state.condition!=='traveling')return{ok:false,state:snapshot()};if(pendingTravel?.cost)state.ship.fuel=Math.min(state.ship.fuelMax,state.ship.fuel+pendingTravel.cost);pendingTravel=null;state={...state,condition:'stationary'};notify();return{ok:true,state:snapshot()};}
function dock(){if(state.condition!=='stationary'||!DOCKABLE.has(state.location)||state.operatorLocation!=='aboard')return{ok:false,state:snapshot()};state={...state,condition:'docked'};save();notify();return{ok:true,state:snapshot()};}
function undock(){if(state.condition!=='docked'||state.operatorLocation!=='aboard')return{ok:false,state:snapshot()};state={...state,condition:'stationary'};save();notify();return{ok:true,state:snapshot()};}
function exitShip(){if(state.condition!=='docked'||state.operatorLocation!=='aboard'||!['haven','meridian','prospect'].includes(state.location))return{ok:false,state:snapshot()};const operatorLocation=state.location==='haven'?'haven-repair-bay':state.location==='meridian'?'meridian-dock':'last-lantern';state={...state,operatorLocation};save();notify();return{ok:true,state:snapshot()};}
function enterHavenCommons(){if(state.location!=='haven'||state.condition!=='docked'||state.operatorLocation!=='haven-repair-bay')return{ok:false,state:snapshot()};ensureBrann();state={...state,operatorLocation:'haven-commons'};state.npcs.brann.memory.lastVisitTrip=state.tripCount;save();notify();return{ok:true,state:snapshot()};}
function leaveHavenCommons(){if(state.location!=='haven'||state.operatorLocation!=='haven-commons')return{ok:false,state:snapshot()};state={...state,operatorLocation:'haven-repair-bay'};save();notify();return{ok:true,state:snapshot()};}
function oldGantryStatus(){ensureStationDevelopment();return JSON.parse(JSON.stringify(state.stationDevelopment.haven.oldGantry));}
function revealOldGantry(){ensureStationDevelopment();ensureMara();const g=state.stationDevelopment.haven.oldGantry;if(state.location!=='haven'||state.operatorLocation!=='haven-repair-bay'||!state.npcs.mara.met||g.status!=='unknown')return{ok:false,state:snapshot()};g.status='revealed';g.revealedTrip=state.tripCount;state.npcs.mara.memory.toldAboutOldGantry=true;save();notify();return{ok:true,state:snapshot()};}
function enterOldGantry(){ensureStationDevelopment();const g=state.stationDevelopment.haven.oldGantry;if(state.location!=='haven'||state.condition!=='docked'||state.operatorLocation!=='haven-repair-bay'||g.status==='unknown')return{ok:false,state:snapshot()};state={...state,operatorLocation:'haven-old-gantry'};save();notify();return{ok:true,state:snapshot()};}
function leaveOldGantry(){if(state.location!=='haven'||state.operatorLocation!=='haven-old-gantry')return{ok:false,state:snapshot()};state={...state,operatorLocation:'haven-repair-bay'};save();notify();return{ok:true,state:snapshot()};}
function inspectOldGantry(){ensureStationDevelopment();const g=state.stationDevelopment.haven.oldGantry;if(state.location!=='haven'||state.operatorLocation!=='haven-old-gantry'||g.status==='unknown')return{ok:false,state:snapshot()};if(g.status!=='inspected'){g.status='inspected';g.inspectedTrip=state.tripCount;save();notify();}return{ok:true,state:snapshot()};}
function learnOldGantryLead(){ensureStationDevelopment();ensureSeli();const g=state.stationDevelopment.haven.oldGantry,place=seliPresence();if(g.status!=='inspected'||!state.npcs.seli.met||!((state.operatorLocation==='meridian-dock'&&place==='meridian')||(state.operatorLocation==='last-lantern'&&place==='prospect')))return{ok:false,state:snapshot()};g.status='lead-known';g.seliLeadKnown=true;g.leadTrip=state.tripCount;state.npcs.seli.memory.gantryAssemblyLead=true;save();notify();return{ok:true,state:snapshot()};}
function deliverGantryAssembly(){ensureStationDevelopment();ensureMara();ensureWorkState();const g=state.stationDevelopment.haven.oldGantry;if(state.location!=='haven'||state.operatorLocation!=='haven-repair-bay'||g.status!=='assembly-aboard'||(state.cargo.gravitonControlAssembly||0)<1)return{ok:false,state:snapshot()};state.cargo.gravitonControlAssembly-=1;if(state.cargo.gravitonControlAssembly<=0)delete state.cargo.gravitonControlAssembly;g.status='restoring';g.assemblyDelivered=true;g.restorationStartTrip=state.tripCount;state.npcs.mara.memory.receivedGantryAssembly=true;save();notify();return{ok:true,state:snapshot()};}
function gantrySupplierStatus(){ensureStationDevelopment();ensureWorkState();const g=state.stationDevelopment.haven.oldGantry;return{known:Boolean(g.seliLeadKnown),purchased:Boolean(g.assemblyPurchased),price:1200,cargoUnits:1,credits:state.credits,cargoUsed:cargoUsed(),cargoCapacity:state.ship.cargoCapacity,canBuy:state.operatorLocation==='meridian-dock'&&g.seliLeadKnown&&!g.assemblyPurchased&&state.credits>=1200&&cargoUsed()<state.ship.cargoCapacity};}
function buyGantryAssembly(){ensureStationDevelopment();ensureWorkState();const q=gantrySupplierStatus(),g=state.stationDevelopment.haven.oldGantry;if(!q.known||q.purchased||state.operatorLocation!=='meridian-dock')return{ok:false,reason:'unavailable',state:snapshot()};if(state.credits<q.price)return{ok:false,reason:'credits',state:snapshot()};if(cargoUsed()>=state.ship.cargoCapacity)return{ok:false,reason:'cargo',state:snapshot()};state.credits-=q.price;state.cargo.gravitonControlAssembly=(state.cargo.gravitonControlAssembly||0)+1;g.status='assembly-aboard';g.assemblyPurchased=true;g.assemblyPurchasedTrip=state.tripCount;save();notify();return{ok:true,state:snapshot()};}
function meetBrann(){ensureBrann();if(state.operatorLocation!=='haven-commons')return{ok:false,state:snapshot()};if(!state.npcs.brann.met){state.npcs.brann.met=true;state.npcs.brann.memory.metTrip=state.tripCount;save();notify();}return{ok:true,state:snapshot()};}
function returnToShip(){if(state.condition!=='docked'||!['haven-repair-bay','meridian-dock','last-lantern'].includes(state.operatorLocation))return{ok:false,state:snapshot()};state={...state,operatorLocation:'aboard'};save();notify();return{ok:true,state:snapshot()};}
function compareOuterBeaconReports(){ensureDiscovery();if(state.location!=='prospect'||state.operatorLocation!=='last-lantern')return{ok:false,state:snapshot()};const d=state.discovery.outerBeacon;if(d.status==='confirmed')return{ok:false,state:snapshot()};d.status='confirmed';d.reportsCompared=3;d.note='Three independent survey crews reported the same faint navigation beacon coordinates beyond regular Prospect lanes.';if(!state.discovery.knownLocations.includes('calder'))state.discovery.knownLocations.push('calder');delete state.contractBoards.prospect;save();notify();return{ok:true,state:snapshot()};}
function advanceCalderSurvey(){
 ensureDiscovery();const d=state.discovery.calderSurvey;
 if(state.location!=='calder'||state.operatorLocation!=='aboard'||state.condition!=='stationary'||d.archiveRecovered)return{ok:false,state:snapshot()};
 if(d.stage==='unexamined')d.stage='array-noticed';
 else if(d.stage==='array-noticed')d.stage='array-identified';
 else if(d.stage==='array-identified'){d.stage='archive-recovered';d.archiveRecovered=true;d.note='A surviving Calder survey archive contains repeated observations at consistent coordinates that do not match anything on Wayfarer charts.';ensureFieldOperation();if(state.fieldOperations.gowlDistress.status==='unavailable'){state.fieldOperations.gowlDistress.status='signal-received';state.fieldOperations.gowlDistress.signalSeen=false;}}
 else return{ok:false,state:snapshot()};
 save();notify();return{ok:true,state:snapshot()};
}
function shareCalderSurveyWithSeli(){
 ensureDiscovery();ensureSeli();const d=state.discovery.calderSurvey;
 if(!d.archiveRecovered||d.sharedWithSeli||state.operatorLocation!=='last-lantern'||seliPresence()!=='prospect')return{ok:false,state:snapshot()};
 d.sharedWithSeli=true;state.npcs.seli.memory.reviewedCalderSurvey=true;save();notify();return{ok:true,state:snapshot()};
}
function seliPresence(){ensureSeli();const seli=state.npcs.seli;if(!seli.met)return'meridian';const eligibleTrip=Number.isFinite(seli.memory.returnEligibleTrip)?seli.memory.returnEligibleTrip:Math.max(0,state.tripCount-2);return state.tripCount>=eligibleTrip?'prospect':'meridian';}
function chooseSeliFirstMeeting(choice){ensureSeli();const seli=state.npcs.seli;if(seli.met||!['share','private'].includes(choice))return{ok:false,state:snapshot()};seli.met=true;seli.memory.metTrip=state.tripCount;seli.memory.returnEligibleTrip=state.tripCount+2;if(choice==='share'){seli.relationship+=1;seli.memory.sharedMarketNotes=true;}else seli.memory.keptNotesPrivate=true;save();notify();return{ok:true,state:snapshot()};}
function acknowledgeSeliReturn(){ensureSeli();const seli=state.npcs.seli;if(!seli.met||seliPresence()!=='prospect')return{ok:false,state:snapshot()};if(!seli.memory.metAtProspect){seli.memory.metAtProspect=true;seli.memory.prospectMeetingTrip=state.tripCount;save();notify();}return{ok:true,state:snapshot()};}
function ensureShipSpecialization(){if(!state.ship.specialization||typeof state.ship.specialization!=='object')state.ship.specialization={installed:null,owned:[]};const spec=state.ship.specialization;if(!Array.isArray(spec.owned))spec.owned=[];spec.owned=[...new Set(spec.owned.filter(id=>['survey-package','freight-handling-package'].includes(id)))];if(!['survey-package','freight-handling-package'].includes(spec.installed))spec.installed=null;if(spec.installed&&!spec.owned.includes(spec.installed))spec.owned.push(spec.installed);}
function shipSpecialization(){ensureShipSpecialization();return JSON.parse(JSON.stringify(state.ship.specialization));}
function configureShip(packageId){ensureShipSpecialization();if(state.activeContract?.requiredPackage&&state.activeContract.requiredPackage!==packageId)return{ok:false,reason:'protected-cargo',state:snapshot()};if(state.location!=='haven'||state.condition!=='docked'||state.operatorLocation!=='haven-repair-bay'||!state.npcs?.mara?.met)return{ok:false,reason:'facility',state:snapshot()};if(!['survey-package','freight-handling-package'].includes(packageId))return{ok:false,reason:'unknown-package',state:snapshot()};const spec=state.ship.specialization;if(!spec.owned.includes(packageId))spec.owned.push(packageId);spec.installed=packageId;save();notify();return{ok:true,state:snapshot()};}
function specializedSurveyStatus(){ensureDiscovery();ensureShipSpecialization();const survey=state.discovery.specializedSurvey;if(!survey)return{known:false,completed:false,capable:false,installed:state.ship.specialization.installed};return{known:true,completed:Boolean(survey.completed),capable:state.ship.specialization.installed==='survey-package',installed:state.ship.specialization.installed};}
function completeSpecializedSurvey(){ensureDiscovery();ensureShipSpecialization();const survey=state.discovery.specializedSurvey;if(!survey||survey.completed||state.location!=='calder'||state.operatorLocation!=='aboard'||state.condition!=='stationary'||state.ship.specialization.installed!=='survey-package')return{ok:false,state:snapshot()};survey.status='completed';survey.completed=true;survey.completedTrip=state.tripCount;survey.note='With the dedicated survey package tied into the surviving Calder array, the Wayfarer resolves a weak repeating return beyond the old archive coordinates. It is too distant to identify, but it is real and persistent.';save();notify();return{ok:true,state:snapshot()};}
function chooseMaraFirstMeeting(choice){ensureMara();const mara=state.npcs.mara;if(mara.met||!['thank','value'].includes(choice)||state.location!=='haven'||state.operatorLocation!=='haven-repair-bay')return{ok:false,state:snapshot()};mara.met=true;mara.memory.firstChoice=choice;mara.memory.metTrip=state.tripCount;if(choice==='thank')mara.memory.thankedForWayfarer=true;else mara.memory.askedWayfarerValue=true;save();notify();return{ok:true,state:snapshot()};}
function repairQuote(){const missing=Math.max(0,state.ship.hullMax-state.ship.hull),affordablePoints=Math.floor(state.credits/REPAIR_COST_PER_POINT),repairPoints=Math.min(missing,affordablePoints);return{missing,repairPoints,cost:repairPoints*REPAIR_COST_PER_POINT,fullCost:missing*REPAIR_COST_PER_POINT,canRepair:repairPoints>0};}
function repairHull(){const quote=repairQuote();if(state.location!=='haven'||!quote.canRepair)return{ok:false,quote};state={...state,credits:state.credits-quote.cost,ship:{...state.ship,hull:state.ship.hull+quote.repairPoints}};save();notify();return{ok:true,quote,state:snapshot()};}
function subscribe(listener){listeners.add(listener);return()=>listeners.delete(listener);}
function backupJSON(){return JSON.stringify(snapshot(),null,2);}
function prepareRestore(text){try{const parsed=migrateIdentity(JSON.parse(String(text||'')));if(!validState(parsed))return{ok:false,reason:'invalid'};return{ok:true,state:typeof structuredClone==='function'?structuredClone(parsed):JSON.parse(JSON.stringify(parsed))};}catch(error){return{ok:false,reason:'invalid'};}}
function restorePrepared(candidate){if(!validState(candidate))return{ok:false,reason:'invalid',state:snapshot()};const replacement=typeof structuredClone==='function'?structuredClone(candidate):JSON.parse(JSON.stringify(candidate));try{localStorage.setItem(STORAGE_KEY,JSON.stringify(replacement));}catch(error){console.error('Restored game could not be written. Current playthrough remains active.',error);return{ok:false,reason:'write-failed',state:snapshot()};}state=replacement;pendingTravel=null;loadFailure=null;notify();return{ok:true,state:snapshot()};}
window.HRState={get:snapshot,seliFreightStatus,acceptSeliReferral,precisionFreightStatus,shipSpecialization,configureShip,specializedSurveyStatus,completeSpecializedSurvey,loadStatus:()=>({ok:!loadFailure,error:loadFailure?String(loadFailure.message||loadFailure):null}),backupJSON,prepareRestore,restorePrepared,completeSetup,beginNewPlaythrough,oldGantryStatus,revealOldGantry,enterOldGantry,leaveOldGantry,inspectOldGantry,learnOldGantryLead,deliverGantryAssembly,gantrySupplierStatus,buyGantryAssembly,fieldOperation,tavyrelContinuity,completeTavyrelReunion,acknowledgeCommunications,respondToDistress,establishDistressContact,resolveDistress,enterHavenCommons,leaveHavenCommons,meetBrann,tradeMarket,observeTradeMarket,marketRecords,buyTradeGood,sellTradeGood,advanceCalderSurvey,shareCalderSurveyWithSeli,beginTravel,completeTravel,cancelTravel,dock,undock,exitShip,returnToShip,compareOuterBeaconReports,chooseSeliFirstMeeting,acknowledgeSeliReturn,seliPresence,chooseMaraFirstMeeting,acceptContract,completeActiveContract,workStatus,travelQuote,refuelQuote,refuelToFull,repairQuote,repairHull,subscribe,save};
})();