(() => {
'use strict';
const $=id=>document.getElementById(id),backdrop=$('focus-backdrop'),panels={engineering:$('engineering-panel'),navigation:$('navigation-panel'),seli:$('seli-panel'),communications:$('communications-panel'),operations:$('operations-panel'),beacon:$('beacon-panel')};
const close={engineering:$('close-engineering'),navigation:$('close-navigation'),seli:$('close-seli'),communications:$('close-communications'),operations:$('close-operations'),beacon:$('close-beacon')};
const LOCATION_NAMES={haven:'Haven Orbit',meridian:'Meridian Exchange',prospect:'Prospect Reach',calder:"Calder's Drift"},CARGO_NAMES={food:'Packaged Food',medicine:'Medicine',machineParts:'Machine Parts',ore:'Processed Ore'};
let activePanel=null,travelInProgress=false,dockingInProgress=false,stationTransitionInProgress=false;
function renderLocation(s){const base=LOCATION_NAMES[s.location]||s.location;$('location-name').textContent=s.condition==='docked'?base+' — Docked':base;const dock=$('dock-button'),dockable=['haven','meridian','prospect'].includes(s.location);dock.textContent=s.condition==='docked'?'Undock':'Dock';dock.hidden=s.operatorLocation!=='aboard'||(!dockable&&s.condition==='stationary');dock.disabled=travelInProgress||dockingInProgress||stationTransitionInProgress||s.operatorLocation!=='aboard'||!['stationary','docked'].includes(s.condition);$('exit-ship-button').hidden=!(s.condition==='docked'&&s.operatorLocation==='aboard'&&['meridian','prospect'].includes(s.location));$('station-ui').hidden=!['meridian-dock','last-lantern'].includes(s.operatorLocation);if(s.operatorLocation==='meridian-dock'){$('station-name').textContent='MERIDIAN EXCHANGE';$('station-area').textContent='Dock';}else if(s.operatorLocation==='last-lantern'){$('station-name').textContent='PROSPECT REACH';$('station-area').textContent='The Last Lantern';}}
function renderEngineering(){const s=HRState.get(),q=HRState.repairQuote();$('hull-value').textContent=s.ship.hull+'%';$('credits-value').textContent=s.credits+' cr';if(q.missing===0){$('repair-copy').textContent='Hull is fully restored. Engineering reports nominal condition.';$('repair-button').textContent='Hull Nominal';$('repair-button').disabled=true;}else if(s.location!=='haven'){$('repair-copy').textContent='Hull service is available at Haven.';$('repair-button').textContent='Service at Haven';$('repair-button').disabled=true;}else{$('repair-copy').textContent='Haven yard can restore '+q.repairPoints+' hull points for '+q.cost+' credits.';$('repair-button').textContent='Repair Hull — '+q.cost+' cr';$('repair-button').disabled=!q.canRepair;}}
function renderNavigation(){const s=HRState.get(),known=s.discovery?.knownLocations||[];$('calder-destination').hidden=!known.includes('calder');$('navigation-copy').textContent='Wayfarer fuel: '+s.ship.fuel+' / '+s.ship.fuelMax+'. Known destinations remain available across the frontier; fuel determines practical range.';document.querySelectorAll('[data-destination]').forEach(b=>{const id=b.dataset.destination;if(id==='calder'&&!known.includes('calder'))return;const q=HRState.travelQuote(id),current=id===s.location;b.disabled=current||!q.ok;b.classList.toggle('current',current);const meta=b.querySelector('.route-meta');if(meta){if(current)meta.textContent='Current location';else if(!Number.isFinite(q.cost))meta.textContent='Route unavailable';else if(q.reserve>0)meta.textContent=q.cost+' fuel · '+q.reserve+' reserve required';else meta.textContent=q.cost+' fuel';}b.title=!current&&!q.ok&&Number.isFinite(q.required)?'Need '+q.required+' fuel including safe reserve':'';});}
function renderSeli(){const state=HRState.get(),s=state.npcs?.seli||{met:false,memory:{}},atProspect=state.operatorLocation==='last-lantern'&&HRState.seliPresence()==='prospect';if(!s.met){$('seli-copy').textContent='Seli Varen is a patient Veylan freight broker who seems to remember every price, promise, and favor that passes through Meridian Exchange.';$('seli-choices').innerHTML='<button type="button" data-seli-choice="share">Share some of your market notes</button><button type="button" data-seli-choice="private">Keep your figures private</button>';return;}if(atProspect){HRState.acknowledgeSeliReturn();const remembered=s.memory?.sharedMarketNotes?'“Wayfarer. Good to see someone who understands that useful information improves when it moves.”':'“Wayfarer. Still keeping your figures close? Fair enough. I remember.”';const frontier=state.discovery?.outerBeacon?.status==='confirmed'?"Seli nods toward the survey tables. “I heard you confirmed Calder. The crews going that way carry their own return reserve—there is no fuel service waiting out there.”":"Seli nods toward the survey tables. “Prospect crews talk before their reports reach any formal board. If several of them repeat the same coordinates, I would listen.”";$('seli-copy').textContent=remembered+' '+frontier;$('seli-choices').innerHTML='<button type="button" data-seli-choice="close">Good to see you, Seli</button>';return;}$('seli-copy').textContent=s.memory?.sharedMarketNotes?'Seli treats you as an operator willing to exchange useful information instead of guarding every advantage.':'Seli respects your discretion, though the Veylan broker has not forgotten that you keep your market information close.';$('seli-choices').innerHTML='<button type="button" data-seli-choice="close">Continue</button>';}
function cargoText(cargo={}){const entries=Object.entries(cargo);return entries.length?entries.map(([id,qty])=>qty+' '+(CARGO_NAMES[id]||id)).join(', '):'Documents / data';}
function renderCommunications(){const s=HRState.get(),w=HRState.workStatus(),active=s.activeContract;if(active){$('communications-copy').innerHTML='<div class="work-card"><strong>'+active.title+' — Active</strong><p>'+active.text+'</p><div class="work-meta"><span>Destination: '+(LOCATION_NAMES[active.destination]||active.destination)+'</span><span>'+active.reward+' cr</span></div></div><p class="work-note">Finish the active job before accepting another posting.</p>';return;}if(!['haven','meridian','prospect'].includes(s.location)){$('communications-copy').innerHTML='<div class="work-card">No local public work board is available here.</div>';return;}const offers=w.offers;$('communications-copy').innerHTML='<p class="work-note">Local postings change as brokers place and close work. Returning after travel may reveal different work.</p>'+offers.map(c=>'<div class="work-card"><strong>'+c.title+'</strong><p>'+c.text+'</p><div class="work-meta"><span>To: '+(LOCATION_NAMES[c.destination]||c.destination)+'</span><span>'+c.reward+' cr</span></div><div class="work-meta"><span>'+cargoText(c.cargo)+'</span><button class="work-accept" type="button" data-contract-id="'+c.id+'">Accept</button></div></div>').join('');}
function renderOperations(){const s=HRState.get(),w=HRState.workStatus(),cargo=Object.entries(s.cargo||{}),fq=HRState.refuelQuote();$('operations-copy').innerHTML='<div class="cargo-meter"><strong>Cargo hold</strong><div>'+w.cargoUsed+' / '+w.cargoCapacity+' spaces used</div>'+(cargo.length?cargo.map(([id,qty])=>'<div>'+(CARGO_NAMES[id]||id)+': '+qty+'</div>').join(''):'<div>Hold empty</div>')+'</div><div class="cargo-meter"><strong>Fuel</strong><div>'+s.ship.fuel+' / '+s.ship.fuelMax+'</div>'+(fq.available?(fq.needed?'<button id="refuel-full" class="work-accept" type="button">Refuel to Full — '+fq.fullCost+' cr</button>':'<div>Tank full</div>'):'<div>'+(['haven','meridian','prospect'].includes(s.location)?'Dock at port for fuel service.':'No fuel service available here.')+'</div>')+'</div><p>Operator standing: <strong>'+s.reputation+'</strong></p>'+(s.activeContract?'<div class="work-card"><strong>'+s.activeContract.title+'</strong><p>'+s.activeContract.text+'</p><div class="work-meta"><span>Destination: '+(LOCATION_NAMES[s.activeContract.destination]||s.activeContract.destination)+'</span><span>'+s.activeContract.reward+' cr</span></div></div>':'<p class="work-note">No active job.</p>');$('complete-active-contract').hidden=!w.canComplete;const refuel=$('refuel-full');if(refuel)refuel.addEventListener('click',()=>{HRState.refuelToFull();renderOperations();});}
function renderBeacon(){const d=HRState.get().discovery?.outerBeacon||{status:'unknown'};if(d.status==='confirmed'){$('beacon-copy').innerHTML='<p>You compared reports from three independent survey crews. The coordinates agree: an old navigation signal is operating beyond the regular Prospect lanes.</p><p><strong>Calder\'s Drift has been added to Wayfarer Navigation.</strong></p>';$('compare-reports').hidden=true;}else{$('beacon-copy').innerHTML='<p>Several survey crews have mentioned a faint navigation beacon beyond the regular Prospect lanes. Most operators dismiss it as an old maintenance marker—but the crews keep giving remarkably similar coordinates.</p><p>One report is a rumor. Comparing independent observations may tell you whether there is actually something there.</p>';$('compare-reports').hidden=false;}}
function openPanel(id){activePanel=id;Object.entries(panels).forEach(([k,p])=>p.hidden=k!==id);if(id==='engineering')renderEngineering();if(id==='navigation')renderNavigation();if(id==='seli')renderSeli();if(id==='communications')renderCommunications();if(id==='operations')renderOperations();if(id==='beacon')renderBeacon();backdrop.hidden=false;document.body.classList.add('panel-open');close[id].focus();}
function closePanel(){if(!activePanel)return;backdrop.hidden=true;Object.values(panels).forEach(p=>p.hidden=true);document.body.classList.remove('panel-open');activePanel=null;}
function consoleIntent(id){if(travelInProgress||dockingInProgress||stationTransitionInProgress||HRState.get().operatorLocation!=='aboard')return;if(['engineering','navigation','operations','communications'].includes(id))openPanel(id);}
window.addEventListener('hr:console',e=>consoleIntent(e.detail.id));window.addEventListener('hr:person',e=>{const s=HRState.get(),place=HRState.seliPresence();if(e.detail.id==='seli'&&((s.operatorLocation==='meridian-dock'&&place==='meridian')||(s.operatorLocation==='last-lantern'&&place==='prospect')))openPanel('seli');});window.addEventListener('hr:world',e=>{const s=HRState.get();if(e.detail.id==='outer-beacon-reports'&&s.operatorLocation==='last-lantern')openPanel('beacon');});
document.querySelectorAll('[data-console]').forEach(b=>b.addEventListener('click',()=>consoleIntent(b.dataset.console)));Object.values(close).forEach(b=>b.addEventListener('click',closePanel));backdrop.addEventListener('click',e=>{if(e.target===backdrop)closePanel();});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!backdrop.hidden)closePanel();});
$('repair-button').addEventListener('click',()=>{HRState.repairHull();renderEngineering();});$('communications-copy').addEventListener('click',e=>{const b=e.target.closest('[data-contract-id]');if(!b)return;const result=HRState.acceptContract(b.dataset.contractId);if(result.ok)renderCommunications();else if(result.reason==='cargo'){$('communications-copy').insertAdjacentHTML('beforeend','<p class="work-note">The Wayfarer does not have enough free cargo space for that job.</p>');}});$('complete-active-contract').addEventListener('click',()=>{if(HRState.completeActiveContract().ok)renderOperations();});
$('seli-choices').addEventListener('click',e=>{const b=e.target.closest('[data-seli-choice]');if(!b)return;if(b.dataset.seliChoice==='close'){closePanel();return;}if(HRState.chooseSeliFirstMeeting(b.dataset.seliChoice).ok)renderSeli();});
$('compare-reports').addEventListener('click',()=>{if(HRState.compareOuterBeaconReports().ok)renderBeacon();});
document.querySelectorAll('[data-destination]').forEach(button=>button.addEventListener('click',async()=>{if(travelInProgress)return;const destination=button.dataset.destination,result=HRState.beginTravel(destination);if(!result.ok)return;travelInProgress=true;closePanel();$('location-name').textContent='In Transit';try{await WayfarerScene.showTravel(result.origin,destination);HRState.completeTravel(destination);}catch(error){console.error('Travel presentation failed.',error);HRState.cancelTravel();}finally{travelInProgress=false;renderLocation(HRState.get());}}));
$('dock-button').addEventListener('click',async()=>{if(travelInProgress||dockingInProgress)return;const before=HRState.get(),mode=before.condition==='docked'?'undock':'dock';if(!['stationary','docked'].includes(before.condition))return;dockingInProgress=true;renderLocation(before);$('location-name').textContent=mode==='dock'?'Docking…':'Undocking…';try{await WayfarerScene.showDocking(mode,before.location);mode==='dock'?HRState.dock():HRState.undock();}finally{dockingInProgress=false;renderLocation(HRState.get());}});
$('exit-ship-button').addEventListener('click',async()=>{const before=HRState.get();if(stationTransitionInProgress||before.condition!=='docked'||before.operatorLocation!=='aboard')return;stationTransitionInProgress=true;try{await WayfarerScene.showStationTransition('LEAVING WAYFARER');HRState.exitShip();}finally{stationTransitionInProgress=false;renderLocation(HRState.get());}});
$('return-ship-button').addEventListener('click',async()=>{if(stationTransitionInProgress)return;stationTransitionInProgress=true;try{HRState.returnToShip();await WayfarerScene.showStationTransition('RETURNING TO WAYFARER');}finally{stationTransitionInProgress=false;renderLocation(HRState.get());}});
HRState.subscribe(s=>{if(!travelInProgress&&!dockingInProgress&&!stationTransitionInProgress)renderLocation(s);if(activePanel==='navigation')renderNavigation();if(activePanel==='beacon')renderBeacon();});
async function start(){try{renderLocation(HRState.get());await WayfarerScene.mount($('scene'));document.body.classList.add('ready');}catch(error){console.error('Wayfarer graphical proof failed to start.',error);$('startup-error').hidden=false;}}
window.HavensReachProof={rebuildRenderer:async()=>{const before=JSON.stringify(HRState.get());await WayfarerScene.destroy();await WayfarerScene.mount($('scene'));const after=JSON.stringify(HRState.get());return{unchanged:before===after,before:JSON.parse(before),after:JSON.parse(after)};}};start();
})();