(() => {
'use strict';
const $=id=>document.getElementById(id),backdrop=$('focus-backdrop'),panels={engineering:$('engineering-panel'),navigation:$('navigation-panel'),seli:$('seli-panel'),communications:$('communications-panel'),operations:$('operations-panel'),beacon:$('beacon-panel')};
const close={engineering:$('close-engineering'),navigation:$('close-navigation'),seli:$('close-seli'),communications:$('close-communications'),operations:$('close-operations'),beacon:$('close-beacon')};
const LOCATION_NAMES={haven:'Haven Orbit',meridian:'Meridian Exchange',prospect:'Prospect Reach',calder:"Calder's Drift"};
let activePanel=null,travelInProgress=false,dockingInProgress=false,stationTransitionInProgress=false;
function renderLocation(s){const base=LOCATION_NAMES[s.location]||s.location;$('location-name').textContent=s.condition==='docked'?base+' — Docked':base;const dock=$('dock-button'),dockable=['haven','meridian','prospect'].includes(s.location);dock.textContent=s.condition==='docked'?'Undock':'Dock';dock.hidden=s.operatorLocation!=='aboard'||(!dockable&&s.condition==='stationary');dock.disabled=travelInProgress||dockingInProgress||stationTransitionInProgress||s.operatorLocation!=='aboard'||!['stationary','docked'].includes(s.condition);$('exit-ship-button').hidden=!(s.condition==='docked'&&s.operatorLocation==='aboard'&&['meridian','prospect'].includes(s.location));$('station-ui').hidden=!['meridian-dock','last-lantern'].includes(s.operatorLocation);if(s.operatorLocation==='meridian-dock'){$('station-name').textContent='MERIDIAN EXCHANGE';$('station-area').textContent='Dock';}else if(s.operatorLocation==='last-lantern'){$('station-name').textContent='PROSPECT REACH';$('station-area').textContent='The Last Lantern';}}
function renderEngineering(){const s=HRState.get(),q=HRState.repairQuote();$('hull-value').textContent=s.ship.hull+'%';$('credits-value').textContent=s.credits+' cr';if(q.missing===0){$('repair-copy').textContent='Hull is fully restored. Engineering reports nominal condition.';$('repair-button').textContent='Hull Nominal';$('repair-button').disabled=true;}else if(s.location!=='haven'){$('repair-copy').textContent='Hull service is available at Haven.';$('repair-button').textContent='Service at Haven';$('repair-button').disabled=true;}else{$('repair-copy').textContent='Haven yard can restore '+q.repairPoints+' hull points for '+q.cost+' credits.';$('repair-button').textContent='Repair Hull — '+q.cost+' cr';$('repair-button').disabled=!q.canRepair;}}
function renderNavigation(){const s=HRState.get(),known=s.discovery?.knownLocations||[];$('calder-destination').hidden=!known.includes('calder');$('navigation-copy').textContent=known.includes('calder')?"Known frontier routes include the newly charted Calder's Drift.":'Prospect Reach is the outer established route. Additional frontier coordinates require reliable evidence.';document.querySelectorAll('[data-destination]').forEach(b=>{b.disabled=b.dataset.destination===s.location;b.classList.toggle('current',b.disabled);});}
function renderSeli(){const s=HRState.get().npcs?.seli||{met:false,memory:{}};if(!s.met){$('seli-copy').textContent='Seli Varen is a patient Veylan freight broker who seems to remember every price, promise, and favor that passes through Meridian Exchange.';$('seli-choices').innerHTML='<button type="button" data-seli-choice="share">Share some of your market notes</button><button type="button" data-seli-choice="private">Keep your figures private</button>';}else{$('seli-copy').textContent=s.memory?.sharedMarketNotes?'Seli treats you as an operator willing to exchange useful information instead of guarding every advantage.':'Seli respects your discretion, though the Veylan broker has not forgotten that you keep your market information close.';$('seli-choices').innerHTML='<button type="button" data-seli-choice="close">Continue</button>';}}
function renderCommunications(){const s=HRState.get(),work=HRState.workStatus().supplyRun,completed=s.completedContracts?.includes(work.id),active=s.activeContract?.id===work.id;if(s.location!=='haven'){$('communications-copy').innerHTML='<div class="work-card">No Haven postings are available on this local link. Return to Haven to review originating work.</div>';$('accept-supply-run').hidden=true;return;}if(active){$('communications-copy').innerHTML='<div class="work-card"><strong>Supply Run — Active</strong><p>'+work.text+'</p></div>';$('accept-supply-run').hidden=true;return;}$('communications-copy').innerHTML='<div class="work-card"><strong>Supply Run</strong><p>'+work.text+'</p><p>Cargo: 2 Packaged Food · Reward: 220 cr</p></div>';$('accept-supply-run').hidden=false;$('accept-supply-run').textContent=completed?'Accept Supply Run Again':'Accept Supply Run';}
function renderOperations(){const s=HRState.get(),w=HRState.workStatus(),food=s.cargo?.food||0;$('operations-copy').innerHTML='<div class="cargo-meter"><strong>Cargo hold</strong><div>'+w.cargoUsed+' / '+w.cargoCapacity+' spaces used</div><div>Packaged Food: '+food+'</div></div><p>Operator standing: <strong>'+s.reputation+'</strong></p>';$('complete-supply-run').hidden=!(s.activeContract?.id==='haven-food'&&s.location==='meridian'&&s.condition==='docked'&&s.operatorLocation==='aboard');}
function renderBeacon(){const d=HRState.get().discovery?.outerBeacon||{status:'unknown'};if(d.status==='confirmed'){$('beacon-copy').innerHTML='<p>You compared reports from three independent survey crews. The coordinates agree: an old navigation signal is operating beyond the regular Prospect lanes.</p><p><strong>Calder\'s Drift has been added to Wayfarer Navigation.</strong></p>';$('compare-reports').hidden=true;}else{$('beacon-copy').innerHTML='<p>Several survey crews have mentioned a faint navigation beacon beyond the regular Prospect lanes. Most operators dismiss it as an old maintenance marker—but the crews keep giving remarkably similar coordinates.</p><p>One report is a rumor. Comparing independent observations may tell you whether there is actually something there.</p>';$('compare-reports').hidden=false;}}
function openPanel(id){activePanel=id;Object.entries(panels).forEach(([k,p])=>p.hidden=k!==id);if(id==='engineering')renderEngineering();if(id==='navigation')renderNavigation();if(id==='seli')renderSeli();if(id==='communications')renderCommunications();if(id==='operations')renderOperations();if(id==='beacon')renderBeacon();backdrop.hidden=false;document.body.classList.add('panel-open');close[id].focus();}
function closePanel(){if(!activePanel)return;backdrop.hidden=true;Object.values(panels).forEach(p=>p.hidden=true);document.body.classList.remove('panel-open');activePanel=null;}
function consoleIntent(id){if(travelInProgress||dockingInProgress||stationTransitionInProgress||HRState.get().operatorLocation!=='aboard')return;if(['engineering','navigation','operations','communications'].includes(id))openPanel(id);}
window.addEventListener('hr:console',e=>consoleIntent(e.detail.id));window.addEventListener('hr:person',e=>{const s=HRState.get();if(e.detail.id==='seli'&&s.operatorLocation==='meridian-dock')openPanel('seli');});window.addEventListener('hr:world',e=>{const s=HRState.get();if(e.detail.id==='outer-beacon-reports'&&s.operatorLocation==='last-lantern')openPanel('beacon');});
document.querySelectorAll('[data-console]').forEach(b=>b.addEventListener('click',()=>consoleIntent(b.dataset.console)));Object.values(close).forEach(b=>b.addEventListener('click',closePanel));backdrop.addEventListener('click',e=>{if(e.target===backdrop)closePanel();});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!backdrop.hidden)closePanel();});
$('repair-button').addEventListener('click',()=>{HRState.repairHull();renderEngineering();});$('accept-supply-run').addEventListener('click',()=>{if(HRState.acceptSupplyRun().ok)renderCommunications();});$('complete-supply-run').addEventListener('click',()=>{if(HRState.completeSupplyRun().ok)renderOperations();});
$('seli-choices').addEventListener('click',e=>{const b=e.target.closest('[data-seli-choice]');if(!b)return;if(b.dataset.seliChoice==='close'){closePanel();return;}if(HRState.chooseSeliFirstMeeting(b.dataset.seliChoice).ok)renderSeli();});
$('compare-reports').addEventListener('click',()=>{if(HRState.compareOuterBeaconReports().ok)renderBeacon();});
document.querySelectorAll('[data-destination]').forEach(button=>button.addEventListener('click',async()=>{if(travelInProgress)return;const destination=button.dataset.destination,result=HRState.beginTravel(destination);if(!result.ok)return;travelInProgress=true;closePanel();$('location-name').textContent='In Transit';try{await WayfarerScene.showTravel(result.origin,destination);HRState.completeTravel(destination);}catch(error){console.error('Travel presentation failed.',error);HRState.cancelTravel();}finally{travelInProgress=false;renderLocation(HRState.get());}}));
$('dock-button').addEventListener('click',async()=>{if(travelInProgress||dockingInProgress)return;const before=HRState.get(),mode=before.condition==='docked'?'undock':'dock';if(!['stationary','docked'].includes(before.condition))return;dockingInProgress=true;renderLocation(before);$('location-name').textContent=mode==='dock'?'Docking…':'Undocking…';try{await WayfarerScene.showDocking(mode,before.location);mode==='dock'?HRState.dock():HRState.undock();}finally{dockingInProgress=false;renderLocation(HRState.get());}});
$('exit-ship-button').addEventListener('click',async()=>{const before=HRState.get();if(stationTransitionInProgress||before.condition!=='docked'||before.operatorLocation!=='aboard')return;stationTransitionInProgress=true;try{await WayfarerScene.showStationTransition('LEAVING WAYFARER');HRState.exitShip();}finally{stationTransitionInProgress=false;renderLocation(HRState.get());}});
$('return-ship-button').addEventListener('click',async()=>{if(stationTransitionInProgress)return;stationTransitionInProgress=true;try{HRState.returnToShip();await WayfarerScene.showStationTransition('RETURNING TO WAYFARER');}finally{stationTransitionInProgress=false;renderLocation(HRState.get());}});
HRState.subscribe(s=>{if(!travelInProgress&&!dockingInProgress&&!stationTransitionInProgress)renderLocation(s);if(activePanel==='navigation')renderNavigation();if(activePanel==='beacon')renderBeacon();});
async function start(){try{renderLocation(HRState.get());await WayfarerScene.mount($('scene'));document.body.classList.add('ready');}catch(error){console.error('Wayfarer graphical proof failed to start.',error);$('startup-error').hidden=false;}}
window.HavensReachProof={rebuildRenderer:async()=>{const before=JSON.stringify(HRState.get());await WayfarerScene.destroy();await WayfarerScene.mount($('scene'));const after=JSON.stringify(HRState.get());return{unchanged:before===after,before:JSON.parse(before),after:JSON.parse(after)};}};start();
})();