(() => {
'use strict';
const DESIGN_W=1536,DESIGN_H=1024,VIEWPORT_CROP={x:160,y:72,w:1230,h:463},VIEWPORT_POLY=[174,82,1350,82,1380,522,170,522];
const VIEWPORT_ASSETS={haven:{stationary:'assets/haven-viewport.webp',docked:'assets/haven-docked-viewport.webp'},meridian:{stationary:'assets/meridian-viewport.webp',docked:'assets/meridian-docked-viewport.webp'},prospect:{stationary:'assets/prospect-arrival-viewport.webp',docked:'assets/prospect-docked-viewport.webp'},calder:{stationary:'assets/calders-drift-arrival-viewport.webp',survey:'assets/calder-survey-array-viewport.webp'},'gowl-distress-field':{stationary:'assets/gowl-debris-field-viewport.webp'}};
const NAMES={haven:'HAVEN',meridian:'MERIDIAN EXCHANGE',prospect:'PROSPECT REACH',calder:"CALDER'S DRIFT",'gowl-distress-field':'DEBRIS FIELD'};
let app=null,host=null,unsubscribe=null,engineeringLamp=null,communicationsLamp=null,engineeringHotspot=null,viewportSprite=null,shipLayer=null,havenLayer=null,meridianLayer=null,lanternLayer=null,commonsLayer=null,gantryLayer=null,meridianSeliGroup=null,prospectSeliGroup=null,tavyrelGroup=null,elapsed=0,cueElapsed=0,cueLayer=null,travelLayer=null,travelResolve=null;
const hotspots=[{id:'operations',label:'Operations / Cargo',x:248,y:520,w:210,h:190},{id:'navigation',label:'Navigation / Helm',x:520,y:520,w:460,h:245},{id:'communications',label:'Communications',x:1020,y:520,w:250,h:190},{id:'engineering',label:'Engineering',x:1050,y:710,w:235,h:165}];
function announce(text){document.getElementById('interaction-label').textContent=text;}
function request(id){window.dispatchEvent(new CustomEvent('hr:console',{detail:{id}}));}
function requestPerson(id){window.dispatchEvent(new CustomEvent('hr:person',{detail:{id}}));}
function requestWorld(id){window.dispatchEvent(new CustomEvent('hr:world',{detail:{id}}));}
function makeHotspot(def){const g=new PIXI.Graphics();g.rect(def.x,def.y,def.w,def.h).fill({color:0xffffff,alpha:.001});g.eventMode='static';g.cursor='pointer';g.on('pointerover',()=>announce(def.label));g.on('pointerout',()=>announce(''));g.on('pointertap',()=>request(def.id));if(def.id==='engineering')engineeringHotspot=g;return g;}
function addDiscoveryCues(){cueLayer=new PIXI.Container();hotspots.forEach((def,index)=>{const cx=def.x+def.w/2,cy=def.y+def.h/2,glow=new PIXI.Graphics();glow.ellipse(cx,cy,def.w*.62,def.h*.58).fill({color:0xf2a84a,alpha:.12});glow.ellipse(cx,cy,def.w*.50,def.h*.46).fill({color:0x78cfe0,alpha:.08});glow.roundRect(def.x-8,def.y-8,def.w+16,def.h+16,18).stroke({color:0xf3b45e,alpha:.62,width:4});glow.alpha=0;glow._cueDelay=index*180;cueLayer.addChild(glow);});app.stage.addChild(cueLayer);}
function updateCondition(state){if(!engineeringLamp)return;const damaged=state.ship.hull<state.ship.hullMax;engineeringLamp.clear();engineeringLamp.circle(1208,728,7).fill({color:damaged?0xff9d2e:0x62d6c7,alpha:.92});engineeringLamp.circle(1208,728,13).stroke({color:damaged?0xff9d2e:0x62d6c7,alpha:.28,width:2});if(engineeringHotspot)engineeringHotspot.accessibleTitle=damaged?'Engineering — hull service needed':'Engineering — hull nominal';if(communicationsLamp){const op=state.fieldOperations?.gowlDistress,unread=op?.status==='signal-received'&&!op?.signalSeen;communicationsLamp.clear();communicationsLamp.circle(1170,585,9).fill({color:unread?0xffb24a:0x35545a,alpha:unread?.98:.35});communicationsLamp.circle(1170,585,17).stroke({color:unread?0xffb24a:0x35545a,alpha:unread?.42:.12,width:3});communicationsLamp.visible=unread;communicationsLamp._unread=unread;}}
async function updateViewport(state){if(!viewportSprite)return;const family=VIEWPORT_ASSETS[state.location]||VIEWPORT_ASSETS.haven,asset=family[state.condition]||family.stationary;viewportSprite.texture=await PIXI.Assets.load(asset);viewportSprite.position.set(VIEWPORT_CROP.x,VIEWPORT_CROP.y);viewportSprite.width=VIEWPORT_CROP.w;viewportSprite.height=VIEWPORT_CROP.h;}
async function showCalderSurveyViewport(){if(!viewportSprite)return;const texture=await PIXI.Assets.load(VIEWPORT_ASSETS.calder.survey);viewportSprite.texture=texture;viewportSprite.position.set(VIEWPORT_CROP.x,VIEWPORT_CROP.y);viewportSprite.width=VIEWPORT_CROP.w;viewportSprite.height=VIEWPORT_CROP.h;}
function sceneSprite(texture){const s=new PIXI.Sprite(texture),cover=Math.max(DESIGN_W/texture.width,DESIGN_H/texture.height);s.scale.set(cover);s.position.set((DESIGN_W-texture.width*cover)/2,(DESIGN_H-texture.height*cover)/2);return s;}
async function mount(target){if(app)await destroy();host=target;app=new PIXI.Application();await app.init({width:DESIGN_W,height:DESIGN_H,background:'#070b12',antialias:true,autoDensity:true,resolution:Math.min(window.devicePixelRatio||1,2)});app.canvas.setAttribute('aria-hidden','true');host.replaceChildren(app.canvas);
const state=window.HRState.get(),family=VIEWPORT_ASSETS[state.location]||VIEWPORT_ASSETS.haven;
const [deckTexture,viewportTexture,havenTexture,maraTexture,stationTexture,seliTexture,lanternTexture,commonsTexture,brannTexture]=await Promise.all([PIXI.Assets.load('assets/wayfarer-command-deck.webp'),PIXI.Assets.load(family[state.condition]||family.stationary),PIXI.Assets.load('assets/haven-repair-bay.webp'),PIXI.Assets.load('assets/mara-quinn-figure.webp'),PIXI.Assets.load('assets/meridian-dock.webp'),PIXI.Assets.load('assets/seli-varen-figure.webp'),PIXI.Assets.load('assets/last-lantern.webp'),PIXI.Assets.load('assets/haven-commons.webp'),PIXI.Assets.load('assets/brann-vek-figure.webp')]);
shipLayer=new PIXI.Container();app.stage.addChild(shipLayer);viewportSprite=new PIXI.Sprite(viewportTexture);viewportSprite.position.set(VIEWPORT_CROP.x,VIEWPORT_CROP.y);viewportSprite.width=VIEWPORT_CROP.w;viewportSprite.height=VIEWPORT_CROP.h;const mask=new PIXI.Graphics();mask.poly(VIEWPORT_POLY).fill(0xffffff);viewportSprite.mask=mask;shipLayer.addChild(viewportSprite,mask);const deck=new PIXI.Sprite(deckTexture);deck.width=DESIGN_W;deck.height=DESIGN_H;shipLayer.addChild(deck);engineeringLamp=new PIXI.Graphics();shipLayer.addChild(engineeringLamp);communicationsLamp=new PIXI.Graphics();shipLayer.addChild(communicationsLamp);hotspots.forEach(def=>shipLayer.addChild(makeHotspot(def)));
const calderHotspot=new PIXI.Graphics();calderHotspot.roundRect(160,72,1230,463,20).fill({color:0xffffff,alpha:.001});calderHotspot.eventMode='static';calderHotspot.cursor='pointer';calderHotspot.on('pointerover',()=>{const s=window.HRState.get();if(s.location==='calder'&&s.condition==='stationary')announce(s.discovery?.calderSurvey?.archiveRecovered?'Calder survey array — archive recovered':'Investigate Calder installation');else if(s.location==='gowl-distress-field'&&s.condition==='stationary')announce('Disabled vessel — open communications');});calderHotspot.on('pointerout',()=>announce(''));calderHotspot.on('pointertap',()=>{const s=window.HRState.get();if(s.location==='calder'&&s.condition==='stationary')requestWorld('calder-installation');else if(s.location==='gowl-distress-field'&&s.condition==='stationary')requestWorld('distress-vessel');});shipLayer.addChild(calderHotspot);
havenLayer=new PIXI.Container();havenLayer.addChild(sceneSprite(havenTexture));const mara=new PIXI.Sprite(maraTexture);mara.anchor.set(.5,1);mara.height=500;mara.scale.x=mara.scale.y;mara.position.set(1180,930);havenLayer.addChild(mara);const mh=new PIXI.Graphics();mh.roundRect(1020,420,320,530,28).fill({color:0xffffff,alpha:.001});mh.eventMode='static';mh.cursor='pointer';mh.on('pointerover',()=>announce('Mara Quinn — Shipwright'));mh.on('pointerout',()=>announce(''));mh.on('pointertap',()=>requestPerson('mara'));havenLayer.addChild(mh);const hft=new PIXI.Text({text:'FREIGHT SERVICES',style:{fontFamily:'Arial, sans-serif',fontSize:25,fill:0xd7fbff,letterSpacing:2,dropShadow:{color:0x041014,alpha:.95,blur:4,distance:2,angle:1.57}}});hft.position.set(185,630);havenLayer.addChild(hft);const hfh=new PIXI.Graphics();hfh.roundRect(145,585,355,250,28).fill({color:0xffffff,alpha:.001});hfh.eventMode='static';hfh.cursor='pointer';hfh.on('pointerover',()=>announce('Haven Freight Services — local market'));hfh.on('pointerout',()=>announce(''));hfh.on('pointertap',()=>requestWorld('freight-market'));havenLayer.addChild(hfh);app.stage.addChild(havenLayer);commonsLayer=new PIXI.Container();commonsLayer.addChild(sceneSprite(commonsTexture));const brann=new PIXI.Sprite(brannTexture);brann.anchor.set(.5,1);brann.height=385;brann.scale.x=brann.scale.y;brann.position.set(650,650);commonsLayer.addChild(brann);const bh=new PIXI.Graphics();bh.roundRect(500,300,300,365,26).fill({color:0xffffff,alpha:.001});bh.eventMode='static';bh.cursor='pointer';bh.on('pointerover',()=>announce('Brann Vek — Commons proprietor'));bh.on('pointerout',()=>announce(''));bh.on('pointertap',()=>requestPerson('brann'));commonsLayer.addChild(bh);const nbh=new PIXI.Graphics();nbh.roundRect(1185,235,350,520,26).fill({color:0xffffff,alpha:.001});nbh.eventMode='static';nbh.cursor='pointer';nbh.on('pointerover',()=>announce('Local News & Notices'));nbh.on('pointerout',()=>announce(''));nbh.on('pointertap',()=>requestWorld('haven-notices'));commonsLayer.addChild(nbh);app.stage.addChild(commonsLayer);
gantryLayer=new PIXI.Container();const gb=new PIXI.Graphics();gb.rect(0,0,DESIGN_W,DESIGN_H).fill(0x11171c);gb.rect(0,700,DESIGN_W,324).fill(0x171d21);gb.rect(150,170,1236,560).stroke({color:0x53616a,width:10,alpha:.7});gb.rect(240,240,1056,420).stroke({color:0x303a41,width:6,alpha:.85});gb.moveTo(320,250).lineTo(320,650).moveTo(1216,250).lineTo(1216,650).stroke({color:0x46535b,width:28,alpha:.9});gb.moveTo(320,300).lineTo(610,510).moveTo(1216,300).lineTo(926,510).stroke({color:0x39464e,width:22,alpha:.9});gb.rect(570,500,396,120).fill({color:0x202a30,alpha:1}).stroke({color:0x56636a,width:5});gantryLayer.addChild(gb);const gt=new PIXI.Text({text:'OLD GANTRY  •  MOTHBALLED',style:{fontFamily:'Arial, sans-serif',fontSize:28,fill:0x9da9ae,letterSpacing:3}});gt.position.set(95,85);gantryLayer.addChild(gt);const gs=new PIXI.Text({text:'Heavy fabrication berth — systems inactive',style:{fontFamily:'Arial, sans-serif',fontSize:21,fill:0x738188}});gs.position.set(98,130);gantryLayer.addChild(gs);const gh=new PIXI.Graphics();gh.roundRect(220,210,1090,470,30).fill({color:0xffffff,alpha:.001});gh.eventMode='static';gh.cursor='pointer';gh.on('pointerover',()=>announce('Inspect the dormant Old Gantry'));gh.on('pointerout',()=>announce(''));gh.on('pointertap',()=>requestWorld('old-gantry-inspect'));gantryLayer.addChild(gh);app.stage.addChild(gantryLayer);
meridianLayer=new PIXI.Container();meridianLayer.addChild(sceneSprite(stationTexture));const seli=new PIXI.Sprite(seliTexture);seli.anchor.set(.5,1);seli.height=430;seli.scale.x=seli.scale.y;seli.position.set(1165,910);meridianSeliGroup=new PIXI.Container();meridianLayer.addChild(meridianSeliGroup);meridianSeliGroup.addChild(seli);const sh=new PIXI.Graphics();sh.roundRect(1015,455,300,475,28).fill({color:0xffffff,alpha:.001});sh.eventMode='static';sh.cursor='pointer';sh.on('pointerover',()=>announce('Seli Varen — Veylan Broker'));sh.on('pointerout',()=>announce(''));sh.on('pointertap',()=>requestPerson('seli'));meridianSeliGroup.addChild(sh);const mft=new PIXI.Text({text:'FREIGHT MARKET',style:{fontFamily:'Arial, sans-serif',fontSize:22,fill:0x9fe3ea,letterSpacing:2}});mft.position.set(190,635);meridianLayer.addChild(mft);const mfh=new PIXI.Graphics();mfh.roundRect(145,585,355,250,28).fill({color:0xffffff,alpha:.001});mfh.eventMode='static';mfh.cursor='pointer';mfh.on('pointerover',()=>announce('Meridian Freight Market — local trade'));mfh.on('pointerout',()=>announce(''));mfh.on('pointertap',()=>requestWorld('freight-market'));meridianLayer.addChild(mfh);app.stage.addChild(meridianLayer);
lanternLayer=new PIXI.Container();lanternLayer.addChild(sceneSprite(lanternTexture));const lead=new PIXI.Graphics();lead.roundRect(850,270,500,330,28).fill({color:0xffffff,alpha:.001});lead.eventMode='static';lead.cursor='pointer';lead.on('pointerover',()=>announce('Survey crews — route talk'));lead.on('pointerout',()=>announce(''));lead.on('pointertap',()=>requestWorld('outer-beacon-reports'));lanternLayer.addChild(lead);prospectSeliGroup=new PIXI.Container();const ps=new PIXI.Sprite(seliTexture);ps.anchor.set(.5,1);ps.height=360;ps.scale.x=ps.scale.y;ps.position.set(390,900);prospectSeliGroup.addChild(ps);const psh=new PIXI.Graphics();psh.roundRect(265,490,250,420,28).fill({color:0xffffff,alpha:.001});psh.eventMode='static';psh.cursor='pointer';psh.on('pointerover',()=>announce('Seli Varen — Veylan Broker'));psh.on('pointerout',()=>announce(''));psh.on('pointertap',()=>requestPerson('seli'));prospectSeliGroup.addChild(psh);lanternLayer.addChild(prospectSeliGroup);
tavyrelGroup=new PIXI.Container();
const tp=new PIXI.Sprite(await PIXI.Assets.load('assets/gowl-distress-operator-portrait.webp'));tp.width=210;tp.height=210;tp.position.set(1040,650);tavyrelGroup.addChild(tp);
const th=new PIXI.Graphics();th.roundRect(1025,635,240,240,24).fill({color:0xffffff,alpha:.001});th.eventMode='static';th.cursor='pointer';th.on('pointerover',()=>announce('Tavyrel — Independent Trader'));th.on('pointerout',()=>announce(''));th.on('pointertap',()=>requestPerson('tavyrel'));tavyrelGroup.addChild(th);lanternLayer.addChild(tavyrelGroup);app.stage.addChild(lanternLayer);

function updateWorld(next){shipLayer.visible=next.operatorLocation==='aboard';havenLayer.visible=next.operatorLocation==='haven-repair-bay';meridianLayer.visible=next.operatorLocation==='meridian-dock';lanternLayer.visible=next.operatorLocation==='last-lantern';commonsLayer.visible=next.operatorLocation==='haven-commons';gantryLayer.visible=next.operatorLocation==='haven-old-gantry';const seliPlace=window.HRState.seliPresence();if(meridianSeliGroup)meridianSeliGroup.visible=seliPlace==='meridian';if(prospectSeliGroup)prospectSeliGroup.visible=seliPlace==='prospect';if(tavyrelGroup)tavyrelGroup.visible=window.HRState.tavyrelContinuity().eligibleForProspectReunion;}
updateCondition(state);updateWorld(state);unsubscribe=window.HRState.subscribe(next=>{updateCondition(next);updateViewport(next);updateWorld(next);});
app.ticker.add(t=>{if(cueLayer){cueElapsed+=t.deltaMS;const fadeIn=650,hold=2600,fadeOut=2200,total=fadeIn+hold+fadeOut+540;cueLayer.children.forEach(c=>{const x=Math.max(0,cueElapsed-c._cueDelay);c.alpha=x<fadeIn?x/fadeIn:(x<fadeIn+hold?.92+Math.sin(x/520)*.08:Math.max(0,1-(x-fadeIn-hold)/fadeOut));});if(cueElapsed>=total){cueLayer.destroy({children:true});cueLayer=null;}}const current=window.HRState.get();if(current.ship.hull>=current.ship.hullMax||matchMedia('(prefers-reduced-motion: reduce)').matches){if(engineeringLamp)engineeringLamp.alpha=1;return;}elapsed+=t.deltaMS;if(engineeringLamp)engineeringLamp.alpha=.82+Math.sin(elapsed/720)*.12;if(communicationsLamp?.visible)communicationsLamp.alpha=.78+Math.sin(elapsed/520)*.18;});}
function showTravel(origin,destination){return new Promise(resolve=>{if(!app){resolve();return;}if(travelLayer)travelLayer.destroy({children:true});travelResolve=resolve;travelLayer=new PIXI.Container();const bg=new PIXI.Graphics();bg.rect(0,0,DESIGN_W,DESIGN_H).fill({color:0x07101a,alpha:.98});const title=new PIXI.Text({text:'ESTABLISHED ROUTE',style:{fontFamily:'Arial, sans-serif',fontSize:28,fill:0xefb25d,letterSpacing:4}});title.position.set(110,105);const from=new PIXI.Text({text:NAMES[origin]||origin.toUpperCase(),style:{fontFamily:'Arial, sans-serif',fontSize:24,fill:0xd8e7e9}});from.position.set(150,690);const to=new PIXI.Text({text:NAMES[destination]||destination.toUpperCase(),style:{fontFamily:'Arial, sans-serif',fontSize:24,fill:0xd8e7e9}});to.anchor.set(1,0);to.position.set(1386,690);const route=new PIXI.Graphics();route.moveTo(230,535).lineTo(1306,535).stroke({color:0x5aa9b7,width:5,alpha:.75});route.circle(230,535,13).fill(0x78cfe0);route.circle(1306,535,13).fill(0x78cfe0);const ship=new PIXI.Graphics();ship.moveTo(0,-16).lineTo(32,0).lineTo(0,16).lineTo(8,0).closePath().fill(0xefb25d);ship.position.set(230,535);const status=new PIXI.Text({text:'WAYFARER  •  IN TRANSIT',style:{fontFamily:'Arial, sans-serif',fontSize:20,fill:0x9fcbd2,letterSpacing:2}});status.anchor.set(.5,0);status.position.set(DESIGN_W/2,790);travelLayer.addChild(bg,title,route,from,to,ship,status);app.stage.addChild(travelLayer);const duration=matchMedia('(prefers-reduced-motion: reduce)').matches?1200:4200,start=performance.now();function frame(now){if(!travelLayer){resolve();return;}const x=Math.min(1,(now-start)/duration),e=x<.5?2*x*x:1-Math.pow(-2*x+2,2)/2;ship.x=230+(1306-230)*e;if(x<1)requestAnimationFrame(frame);else{const done=travelResolve;travelResolve=null;travelLayer.destroy({children:true});travelLayer=null;if(done)done();}}requestAnimationFrame(frame);});}
function showDocking(mode,location){return new Promise(resolve=>{if(!app){resolve();return;}const layer=new PIXI.Container(),veil=new PIXI.Graphics();veil.rect(0,0,DESIGN_W,DESIGN_H).fill({color:0x050a0f,alpha:.72});const title=new PIXI.Text({text:mode==='dock'?'DOCKING APPROACH':'UNDOCKING',style:{fontFamily:'Arial, sans-serif',fontSize:30,fill:0xefb25d,letterSpacing:4}});title.anchor.set(.5);title.position.set(DESIGN_W/2,450);const sub=new PIXI.Text({text:(NAMES[location]||location.toUpperCase())+'  •  WAYFARER',style:{fontFamily:'Arial, sans-serif',fontSize:20,fill:0xb9dce1,letterSpacing:2}});sub.anchor.set(.5);sub.position.set(DESIGN_W/2,500);layer.addChild(veil,title,sub);app.stage.addChild(layer);setTimeout(()=>{layer.destroy({children:true});resolve();},matchMedia('(prefers-reduced-motion: reduce)').matches?700:2200);});}
function showStationTransition(label){return new Promise(resolve=>{if(!app){resolve();return;}const layer=new PIXI.Container(),veil=new PIXI.Graphics();veil.rect(0,0,DESIGN_W,DESIGN_H).fill({color:0x05090d,alpha:.92});const txt=new PIXI.Text({text:label,style:{fontFamily:'Arial, sans-serif',fontSize:28,fill:0xefb25d,letterSpacing:4}});txt.anchor.set(.5);txt.position.set(DESIGN_W/2,DESIGN_H/2);layer.addChild(veil,txt);app.stage.addChild(layer);setTimeout(()=>{layer.destroy({children:true});resolve();},matchMedia('(prefers-reduced-motion: reduce)').matches?350:900);});}
async function destroy(){if(unsubscribe)unsubscribe();unsubscribe=null;if(travelResolve){travelResolve();travelResolve=null;}if(travelLayer){travelLayer.destroy({children:true});travelLayer=null;}engineeringLamp=communicationsLamp=engineeringHotspot=viewportSprite=shipLayer=havenLayer=meridianLayer=lanternLayer=commonsLayer=gantryLayer=meridianSeliGroup=prospectSeliGroup=tavyrelGroup=cueLayer=null;elapsed=cueElapsed=0;if(app){app.destroy(true,{children:true});app=null;}if(host)host.replaceChildren();}
window.WayfarerScene={mount,destroy,showTravel,showDocking,showStationTransition,showCalderSurveyViewport,restoreViewport:()=>updateViewport(window.HRState.get())};
})();